require('../app/config/database');
const District = require('../app/models/district');

const data = [
    { name: 'Albufereta', city: 'Alicante'},
    { name: 'Alipark', city: 'Alicante'},
    { name: 'Altozano-Conde Lumiares', city: 'Alicante'},
    { name: 'Benalúa', city: 'Alicante'},
    { name: 'Cabo de las Huertas', city: 'Alicante'},
    { name: 'Campoamor', city: 'Alicante'},
    { name: 'Carolinas Altas', city: 'Alicante'},
    { name: 'Carolinas Bajas', city: 'Alicante'},
    { name: 'Casco Antiguo-Santa Cruz', city: 'Alicante'},
    { name: 'Centro', city: 'Alicante'},
    { name: 'Ciudad de Asís', city: 'Alicante'},
    { name: 'Ciudad Jardín', city: 'Alicante'},
    { name: 'Colonia Requena', city: 'Alicante'},
    { name: 'Cuatrocientas Viviendas', city: 'Alicante'},
    { name: 'Divina Pastora', city: 'Alicante'},
    { name: 'El Palmeral-Urbanova-Tabarca', city: 'Alicante'},
    { name: 'Ensanche Diputación', city: 'Alicante'},
    { name: 'Florida Alta', city: 'Alicante'},
    { name: 'Florida Baja', city: 'Alicante'},
    { name: 'Garbinet', city: 'Alicante'},
    { name: 'Juan XXIII', city: 'Alicante'},
    { name: 'Lo Morant-Sant Nicolás de Bari', city: 'Alicante'},
    { name: 'Los Ángeles', city: 'Alicante'},
    { name: 'Mercado', city: 'Alicante'},
    { name: 'Pla del Bon Repós', city: 'Alicante'},
    { name: 'Playa San Juan', city: 'Alicante'},
    { name: 'Polígono Babel', city: 'Alicante'},
    { name: 'Polígono San Blas', city: 'Alicante'},
    { name: 'Rabasa', city: 'Alicante'},
    { name: 'Raval Roig-Virgen del Socorro', city: 'Alicante'},
    { name: 'San Agustín', city: 'Alicante'},
    { name: 'San Antón', city: 'Alicante'},
    { name: 'San Blas-Santo Domingo', city: 'Alicante'},
    { name: 'San Fernando-Princesa Mercedes', city: 'Alicante'},
    { name: 'San Gabriel', city: 'Alicante'},
    { name: 'Sidi Ifni-Nou Alacant', city: 'Alicante'},
    { name: 'Tómbola', city: 'Alicante'},
    { name: 'Villafranqueza', city: 'Alicante'},
    { name: 'Virgen del Carmen', city: 'Alicante'},
    { name: 'Virgen del Remedio', city: 'Alicante'},
    { name: 'Vistahermosa', city: 'Alicante'},

    { name: 'Ciutat Vella,el Barri Gòtic', city: 'Barcelona'},
    { name: 'Ciutat Vella,el Raval', city: 'Barcelona'},
    { name: 'Ciutat Vella,la Barceloneta', city: 'Barcelona'},
    { name: 'Ciutat Vella,Sant Pere, Santa Caterina i la Ribera', city: 'Barcelona'},
    { name: 'Eixample,el Fort Pienc', city: 'Barcelona'},
    { name: "Eixample,la Dreta de l'Eixample", city: 'Barcelona'},
    { name: "Eixample,la Nova Esquerra de l'Eixample", city: 'Barcelona'},
    { name: "Eixample,l'Antiga Esquerra de l'Eixample", city: 'Barcelona'},
    { name: 'Eixample,la Sagrada Família', city: 'Barcelona'},
    { name: 'Eixample,Sant Antoni', city: 'Barcelona'},
    { name: "Gràcia,el Camp d'en Grassot i Gràcia Nova", city: 'Barcelona'},
    { name: "Gràcia,el Coll", city: 'Barcelona'},
    { name: 'Gràcia,la Salut', city: 'Barcelona'},
    { name: 'Gràcia,la Vila de Gràcia', city: 'Barcelona'},
    { name: 'Gràcia,Vallcarca i els Penitents', city: 'Barcelona'},
    { name: 'Horta-Guinardó,Can Baró', city: 'Barcelona'},
    { name: 'Horta-Guinardó,el Baix Guinardó', city: 'Barcelona'},
    { name: 'Horta-Guinardó,el Carmel', city: 'Barcelona'},
    { name: 'Horta-Guinardó,el Guinardó', city: 'Barcelona'},
    { name: 'Horta-Guinardó,Horta', city: 'Barcelona'},
    { name: 'Horta-Guinardó,la Clota', city: 'Barcelona'},
    { name: "Horta-Guinardó,la Font d'en Fargues", city: 'Barcelona'},
    { name: 'Horta-Guinardó,la Teixonera', city: 'Barcelona'},
    { name: "Horta-Guinardó,la Vall d'Hebron", city: 'Barcelona'},
    { name: "Horta-Guinardó,Montbau", city: 'Barcelona'},
    { name: 'Horta-Guinardó,Sant Genís dels Agudells', city: 'Barcelona'},
    { name: 'Les Corts,la Maternitat i Sant Ramon', city: 'Barcelona'},
    { name: 'Les Corts,les Corts', city: 'Barcelona'},
    { name: 'Les Corts,Pedralbes', city: 'Barcelona'},
    { name: 'Nou Barris,Can Peguera', city: 'Barcelona'},
    { name: 'Nou Barris,Canyelles', city: 'Barcelona'},
    { name: 'Nou Barris,Ciutat Meridiana', city: 'Barcelona'},
    { name: 'Nou Barris,el Turó de la Peira', city: 'Barcelona'},
    { name: 'Nou Barris,la Guineueta', city: 'Barcelona'},
    { name: 'Nou Barris,la Prosperitat', city: 'Barcelona'},
    { name: 'Nou Barris,la Trinitat Nova', city: 'Barcelona'},
    { name: 'Nou Barris,les Roquetes', city: 'Barcelona'},
    { name: 'Nou Barris,Porta', city: 'Barcelona'},
    { name: 'Nou Barris,Torre Baró', city: 'Barcelona'},
    { name: 'Nou Barris,Vallbona', city: 'Barcelona'},
    { name: 'Nou Barris,Verdun', city: 'Barcelona'},
    { name: 'Nou Barris,Vilapicina i la Torre Llobeta', city: 'Barcelona'},
    { name: 'Sant Andreu,Baró de Viver', city: 'Barcelona'},
    { name: 'Sant Andreu,el Bon Pastor', city: 'Barcelona'},
    { name: 'Sant Andreu,el Congrés i els Indians', city: 'Barcelona'},
    { name: 'Sant Andreu,la Sagrera', city: 'Barcelona'},
    { name: 'Sant Andreu,la Trinitat Vella', city: 'Barcelona'},
    { name: 'Sant Andreu,Navas', city: 'Barcelona'},
    { name: 'Sant Andreu,Sant Andreu', city: 'Barcelona'},
    { name: 'Sant Martí,Diagonal Mar i el Front Marítim del Poblenou', city: 'Barcelona'},
    { name: 'Sant Martí,el Besòs i el Maresme', city: 'Barcelona'},
    { name: "Sant Martí,el Camp de l'Arpa del Clot", city: 'Barcelona'},
    { name: 'Sant Martí,el Clot', city: 'Barcelona'},
    { name: 'Sant Martí,el Parc i la Llacuna del Poblenou', city: 'Barcelona'},
    { name: 'Sant Martí,el Poblenou', city: 'Barcelona'},
    { name: 'Sant Martí,la Verneda i la Pau', city: 'Barcelona'},
    { name: 'Sant Martí,la Vila Olímpica del Poblenou', city: 'Barcelona'},
    { name: 'Sant Martí,Provençals del Poblenou', city: 'Barcelona'},
    { name: 'Sant Martí,Sant Martí de Provençals', city: 'Barcelona'},
    { name: 'Sants-Montjuic,el Poble Sec', city: 'Barcelona'},
    { name: 'Sants-Montjuic,Hostafrancs', city: 'Barcelona'},
    { name: 'Sants-Montjuic,la Bordeta', city: 'Barcelona'},
    { name: 'Sants-Montjuic,la Font de la Guatlla', city: 'Barcelona'},
    { name: 'Sants-Montjuic,la Marina del Prat Vermell', city: 'Barcelona'},
    { name: 'Sants-Montjuic,la Marina de Port', city: 'Barcelona'},
    { name: 'Sants-Montjuic,Sants', city: 'Barcelona'},
    { name: 'Sants-Montjuic,Sants - Badal', city: 'Barcelona'},
    { name: 'Sarrià-Sant Gervasi,el Putxet i el Farró', city: 'Barcelona'},
    { name: 'Sarrià-Sant Gervasi,les Tres Torres', city: 'Barcelona'},
    { name: 'Sarrià-Sant Gervasi,Sant Gervasi - Galvany', city: 'Barcelona'},
    { name: 'Sarrià-Sant Gervasi,Sant Gervasi - la Bonanova', city: 'Barcelona'},
    { name: 'Sarrià-Sant Gervasi,Sarrià', city: 'Barcelona'},
    { name: 'Sarrià-Sant Gervasi,Vallvidrera, el Tibidabo i les Planes', city: 'Barcelona'},

    { name: 'Deusto,Arangoiti', city: 'Bilbao'},
    { name: 'Deusto,Ibarrekolanda', city: 'Bilbao'},
    { name: 'Deusto,San Ignacio', city: 'Bilbao'},
    { name: 'Deusto,San Pedro de Deusto-La Ribera', city: 'Bilbao'},
    { name: 'Uríbarri,Castaños', city: 'Bilbao'},
    { name: 'Uríbarri, Matico-Ciudad Jardín', city: 'Bilbao'},
    { name: 'Uríbarri, Uríbarri', city: 'Bilbao'},
    { name: 'Uríbarri,Zurbaran-Arabella', city: 'Bilbao'},
    { name: 'Otxarcoaga-Txurdinaga, Otxarkoaga', city: 'Bilbao'},
    { name: 'Otxarcoaga-Txurdinaga,Txurdinaga', city: 'Bilbao'},
    { name: 'Begoña, Begoña', city: 'Bilbao'},
    { name: 'Begoña, Bolueta', city: 'Bilbao'},
    { name: 'Begoña, Santutxu', city: 'Bilbao'},
    { name: 'Ibaiondo,Atxuri', city: 'Bilbao'},
    { name: 'Ibaiondo,Bilbao La Vieja', city: 'Bilbao'},
    { name: 'Ibaiondo,Casco Vieja', city: 'Bilbao'},
    { name: 'Ibaiondo,Iturralde', city: 'Bilbao'},
    { name: 'Ibaiondo,La Peña', city: 'Bilbao'},
    { name: 'Ibaiondo,Miribilla', city: 'Bilbao'},
    { name: 'Ibaiondo,San Adrián', city: 'Bilbao'},
    { name: 'Ibaiondo,San Francisco', city: 'Bilbao'},
    { name: 'Ibaiondo,Buia', city: 'Bilbao'},
    { name: 'Ibaiondo,Solocoeche', city: 'Bilbao'},
    { name: 'Ibaiondo,Zabala', city: 'Bilbao'},
    { name: 'Abando,Abando', city: 'Bilbao'},
    { name: 'Abando, Indautxu', city: 'Bilbao'},
    { name: 'Rekalde,Amézola', city: 'Bilbao'},
    { name: 'Rekalde,Iralabarri', city: 'Bilbao'},
    { name: 'Rekalde,Iturrigorri-Peñascal', city: 'Bilbao'},
    { name: 'Rekalde,Rekaldeberri-Larrasquitu', city: 'Bilbao'},
    { name: 'Rekalde,Uretamendi', city: 'Bilbao'},
    { name: 'Basurto-Zorroza,Altamira', city: 'Bilbao'},
    { name: 'Basurto-Zorroza,Basurto', city: 'Bilbao'},
    { name: 'Basurto-Zorroza,Olabeaga', city: 'Bilbao'},
    { name: 'Basurto-Zorroza,Masustegui-Monte Caramelo', city: 'Bilbao'},
    { name: 'Basurto-Zorroza,Zorroza', city: 'Bilbao'},

    { name: 'Centro,San Basilio', city: 'Córdoba'},
    { name: 'Centro,Huerta del Rey-Vallellano', city: 'Córdoba'},
    { name: 'Centro,La Catedral', city: 'Córdoba'},
    { name: 'Centro,San Francisco-Ribera', city: 'Córdoba'},
    { name: 'Centro,Santiago', city: 'Córdoba'},
    { name: 'Centro,San Pedro', city: 'Córdoba'},
    { name: 'Centro,El Salvador y la Compañía', city: 'Córdoba'},
    { name: 'Centro,La Trinidad', city: 'Córdoba'},
    { name: 'Centro,Centro Comercial', city: 'Córdoba'},
    { name: 'Centro,San Miguel-Capuchinos', city: 'Córdoba'},
    { name: 'Centro,San Andrés-San Pablo', city: 'Córdoba'},
    { name: 'Centro,La Magdalena', city: 'Córdoba'},
    { name: 'Centro,Cerro de la Golondrina-Salesianos', city: 'Córdoba'},
    { name: 'Centro,San Lorenzo', city: 'Córdoba'},
    { name: 'Centro,Santa Marina', city: 'Córdoba'},
    { name: 'Centro,Campo de la Merced-Molinos Alta', city: 'Córdoba'},
    { name: 'Centro,Ollerías', city: 'Córdoba'},
    { name: 'Centro,El Carmen', city: 'Córdoba'},
    { name: 'Levante,Viñuela-Rescatado', city: 'Córdoba'},
    { name: 'Levante,Fuensantilla-Edisol', city: 'Córdoba'},
    { name: 'Levante,Sagunto', city: 'Córdoba'},
    { name: 'Levante,Levante', city: 'Córdoba'},
    { name: 'Levante,Fátima', city: 'Córdoba'},
    { name: 'Levante,Zumbacón-Gavilán', city: 'Córdoba'},
    { name: 'Noroeste,Huerta de la Reina', city: 'Córdoba'},
    { name: 'Noroeste,Las Margaritas', city: 'Córdoba'},
    { name: 'Noroeste,Moreras', city: 'Córdoba'},
    { name: 'Noroeste,Arruzafilla', city: 'Córdoba'},
    { name: 'Noroeste,Arroyo del Moro', city: 'Córdoba'},
    { name: 'Noroeste,Parque Figueroa', city: 'Córdoba'},
    { name: 'Noroeste,Huerta de Santa Isabel', city: 'Córdoba'},
    { name: 'Norte-Sierra,Valdeolleros', city: 'Córdoba'},
    { name: 'Norte-Sierra,Santa Rosa', city: 'Córdoba'},
    { name: 'Norte-Sierra,Asomadilla', city: 'Córdoba'},
    { name: 'Norte-Sierra,Cámping', city: 'Córdoba'},
    { name: 'Norte-Sierra,El Tablero', city: 'Córdoba'},
    { name: 'Norte-Sierra,El Patriarca', city: 'Córdoba'},
    { name: 'Norte-Sierra,El Brillante', city: 'Córdoba'},
    { name: 'Norte-Sierra,El Naranjo', city: 'Córdoba'},
    { name: 'Norte-Sierra,Huerta de San Rafael', city: 'Córdoba'},
    { name: 'Poniente-Norte,Parque Azahara', city: 'Córdoba'},
    { name: 'Poniente-Norte,Electromecánicas', city: 'Córdoba'},
    { name: 'Poniente-Norte,Palmeras', city: 'Córdoba'},
    { name: 'Poniente-Norte,Miralbaida', city: 'Córdoba'},
    { name: 'Poniente-Norte,San Rafael de la Albaida', city: 'Córdoba'},
    { name: 'Poniente Sur,Parque Cruz Conde', city: 'Córdoba'},
    { name: 'Poniente Sur,Vista Alegre', city: 'Córdoba'},
    { name: 'Poniente Sur,Polígono de Poniente', city: 'Córdoba'},
    { name: 'Poniente Sur,Huerta de la Marquesa', city: 'Córdoba'},
    { name: 'Poniente Sur,Ciudad Jardín', city: 'Córdoba'},
    { name: 'Poniente Sur,Cercadilla-Medina Azahara', city: 'Córdoba'},
    { name: 'Poniente Sur,Olivos Borrachos', city: 'Córdoba'},
    { name: 'Sur,Guadalquivir', city: 'Córdoba'},
    { name: 'Sur,Sector Sur', city: 'Córdoba'},
    { name: 'Sur,Fray Albino', city: 'Córdoba'},
    { name: 'Sur,Campo de la Verdad-Miraflores', city: 'Córdoba'},
    { name: 'Sureste,El Arenal', city: 'Córdoba'},
    { name: 'Sureste,Arcángel', city: 'Córdoba'},
    { name: 'Sureste,Santuario', city: 'Córdoba'},
    { name: 'Sureste,Fuensanta', city: 'Córdoba'},
    { name: 'Sureste,Cañero', city: 'Córdoba'},
    { name: 'Sureste,Fidiana', city: 'Córdoba'},
    { name: 'Periurbano Este-Campiña', city: 'Córdoba'},
    { name: 'Periurbano Oeste-Sierra', city: 'Córdoba'},

    { name: 'Centro - Altabix Norte,Centro La Vila – La Zapatillera', city: 'Elche'},
    { name: 'Centro - Altabix Norte,Altabix – La Lonja', city: 'Elche'},
    { name: 'Centro - Altabix Norte,Nuevo Altabix – Ciudad Deportiva', city: 'Elche'},
    { name: 'Centro - Altabix Norte,Plaza de Castilla', city: 'Elche'},
    { name: 'Centro - Altabix Sur,El Salvador – La Glorieta', city: 'Elche'},
    { name: 'Centro - Altabix Sur,Jesuitinas – Ripoll', city: 'Elche'},
    { name: 'Centro - Altabix Sur,Ciudad Jardín – Polígono de Altabix', city: 'Elche'},
    { name: 'Centro - Altabix Sur,Travalón – Campo de Fútbol', city: 'Elche'},
    { name: 'Centro - Altabix Sur,San Antón', city: 'Elche'},
    { name: 'Centro - Altabix Sur,Los Palmerales', city: 'Elche'},
    { name: 'Centro - Altabix Sur,Portalada – Portes Encarnades', city: 'Elche'},
    { name: 'Centro - Altabix Sur,El Raval', city: 'Elche'},
    { name: 'Carrús Este,Casablanca – La Rata', city: 'Elche'},
    { name: 'Carrús Este,Camí dels Magros', city: 'Elche'},
    { name: 'Carrús Este,Plaza de Barcelona', city: 'Elche'},
    { name: 'Carrús Este,Plaza 1º de Mayo', city: 'Elche'},
    { name: 'Carrús Este,San Crispín – Polígono de Carrús', city: 'Elche'},
    { name: 'Carrús Oeste,El Toscar', city: 'Elche'},
    { name: 'Carrús Oeste,L’Algeps – Sagrada Familia', city: 'Elche'},
    { name: 'Carrús Oeste,Carrús Oeste', city: 'Elche'},
    { name: 'Carrús Oeste,Cementerio – Corts Valencianes', city: 'Elche'},
    { name: 'Pla Norte,El Corazón de Jesús', city: 'Elche'},
    { name: 'Pla Norte,Obispo Siuri', city: 'Elche'},
    { name: 'Pla Norte,El Pla', city: 'Elche'},
    { name: 'Pla Norte,Pla Oest', city: 'Elche'},
    { name: 'Pla Sur,San José', city: 'Elche'},
    { name: 'Pla Sur,La Torre', city: 'Elche'},
    { name: 'Pla Sur,Plaza de Crevillent', city: 'Elche'},
    { name: 'Pla Sur,El Canal', city: 'Elche'},
    { name: 'Pla Sur,Sector V', city: 'Elche'},
]

const importData = () => {
    District.insertMany(data, function (err, docs) {
        if (err){ 
            return console.error(err);
        } else {
          console.log("Multiple documents inserted to Collection");
        }
    });
}

importData()