require('../app/config/database');
const District = require('../app/services/district');
const City = require('../app/services/city');

const data = [

    { name: 'Ensanche-Juan Florez', city: 'A Coruña' },
    { name: 'Monte Alto-Zalaeta-Atocha', city: 'A Coruña' },
    { name: 'Ciudad Vieja-Centro', city: 'A Coruña' },
    { name: 'Riazor-Los Rosales', city: 'A Coruña' },
    { name: 'Cuatro Caminos-Plaza de la Cubela', city: 'A Coruña' },
    { name: 'Los Castros-Castrillón-Eiris', city: 'A Coruña' },
    { name: 'Agra del Orzán-Ventorrillo', city: 'A Coruña' },
    { name: 'Someso-Matogrande', city: 'A Coruña' },
    { name: 'Os Mallos', city: 'A Coruña' },

    { name: 'Villacerrada-Centro', city: 'Albacete' },
    { name: 'La Pajarita', city: 'Albacete' },
    { name: 'Carretas-Huerta de Marzo', city: 'Albacete' },
    { name: 'Hospital-Parque Sur', city: 'Albacete' },
    { name: 'Franciscanos', city: 'Albacete' },
    { name: 'Fátima', city: 'Albacete' },
    { name: 'Feria', city: 'Albacete' },
    { name: 'Industria-Los Llanos', city: 'Albacete' },
    { name: 'San Antonio Abad-Polígono San Antón', city: 'Albacete' },
    { name: 'Hermanos Falcó-Sepulcro Bolera', city: 'Albacete' },
    { name: 'El Pilar', city: 'Albacete' },
    { name: 'San Pablo-Santa Teresa', city: 'Albacete' },

    { name: 'Albufereta', city: 'Alicante' },
    { name: 'Alipark', city: 'Alicante' },
    { name: 'Altozano-Conde Lumiares', city: 'Alicante' },
    { name: 'Benalúa', city: 'Alicante' },
    { name: 'Cabo de las Huertas', city: 'Alicante' },
    { name: 'Campoamor', city: 'Alicante' },
    { name: 'Carolinas Altas', city: 'Alicante' },
    { name: 'Carolinas Bajas', city: 'Alicante' },
    { name: 'Casco Antiguo-Santa Cruz', city: 'Alicante' },
    { name: 'Centro', city: 'Alicante' },
    { name: 'Ciudad de Asís', city: 'Alicante' },
    { name: 'Ciudad Jardín', city: 'Alicante' },
    { name: 'Colonia Requena', city: 'Alicante' },
    { name: 'Divina Pastora', city: 'Alicante' },
    { name: 'El Palmeral-Urbanova-Tabarca', city: 'Alicante' },
    { name: 'Ensanche Diputación', city: 'Alicante' },
    { name: 'La Florida', city: 'Alicante' },
    { name: 'La Florida Portazgo', city: 'Alicante' },
    { name: 'Garbinet-Parque de las Avenidas', city: 'Alicante' },
    { name: 'Juan XXIII', city: 'Alicante' },
    { name: 'Lo Morant-Sant Nicolás de Bari', city: 'Alicante' },
    { name: 'Los Ángeles', city: 'Alicante' },
    { name: 'Mercado', city: 'Alicante' },
    { name: 'Pla del Bon Repós', city: 'Alicante' },
    { name: 'Playa San Juan', city: 'Alicante' },
    { name: 'Polígono Babel', city: 'Alicante' },
    { name: 'Polígono San Blas', city: 'Alicante' },
    { name: 'Rabasa', city: 'Alicante' },
    { name: 'Raval Roig-Virgen del Socorro', city: 'Alicante' },
    { name: 'San Agustín', city: 'Alicante' },
    { name: 'San Antón', city: 'Alicante' },
    { name: 'San Blas-Santo Domingo', city: 'Alicante' },
    { name: 'San Fernando-Princesa Mercedes', city: 'Alicante' },
    { name: 'San Gabriel', city: 'Alicante' },
    { name: 'Nou Alacant', city: 'Alicante' },
    { name: 'Tómbola', city: 'Alicante' },
    { name: 'Villafranqueza', city: 'Alicante' },
    { name: 'Virgen del Carmen', city: 'Alicante' },
    { name: 'Virgen del Remedio', city: 'Alicante' },
    { name: 'Vistahermosa', city: 'Alicante' },
    { name: 'Murallas', city: 'Alicante' },

    { name: 'Centro', city: 'Almería' },
    { name: 'Centro-Rambla', city: 'Almería' },
    { name: 'Plaza de Toros', city: 'Almería' },
    { name: 'Esperanza-Quemadero', city: 'Almería' },
    { name: 'Altamira-Oliveros-Barrio Alto', city: 'Almería' },
    { name: 'Nueva Andalucía-Regiones', city: 'Almería' },
    { name: 'Ciudad Jardín-Tagarete', city: 'Almería' },
    { name: 'Zapillo', city: 'Almería' },
    { name: 'Vega de Acá-Nueva Almería-Cortijo Grande', city: 'Almería' },
    { name: 'San Luis-Los Molinos', city: 'Almería' },
    { name: 'Villablanca-Cárdenas', city: 'Almería' },
    { name: 'Los Ángeles-Cruz de Caravaca-Piedras Redondas', city: 'Almería' },

    { name: 'Casco Antiguo-Centro', city: 'Avilés' },

    { name: 'Santa Marina-La Paz', city: 'Badajoz' },
    { name: 'Pardaleras', city: 'Badajoz' },
    { name: 'Huerta Rosales-Valdepasillas', city: 'Badajoz' },
    { name: 'María Auxiliadora-Barriada Llera', city: 'Badajoz' },
    { name: 'Ciudad Jardín', city: 'Badajoz' },
    { name: 'San Roque-Ronda Norte', city: 'Badajoz' },
    { name: 'Avenida Elvas', city: 'Badajoz' },
    { name: 'La Estación', city: 'Badajoz' },

    { name: 'Barbastro', city: 'Barbastro' },

    { name: 'Ciutat Vella,el Barri Gòtic', city: 'Barcelona' },
    { name: 'Ciutat Vella,el Raval', city: 'Barcelona' },
    { name: 'Ciutat Vella,la Barceloneta', city: 'Barcelona' },
    { name: 'Ciutat Vella,Sant Pere i Santa Caterina i la Ribera', city: 'Barcelona' },
    { name: 'Eixample,el Fort Pienc', city: 'Barcelona' },
    { name: "Eixample,la Dreta de l'Eixample", city: 'Barcelona' },
    { name: "Eixample,la Nova Esquerra de l'Eixample", city: 'Barcelona' },
    { name: `Eixample,l"Antiga Esquerra de l'Eixample`, city: 'Barcelona' },
    { name: 'Eixample,la Sagrada Família', city: 'Barcelona' },
    { name: 'Eixample,Sant Antoni', city: 'Barcelona' },
    { name: `Gràcia,el Camp d'en Grassot i Gràcia Nova`, city: 'Barcelona' },
    { name: 'Gràcia,el Coll', city: 'Barcelona' },
    { name: 'Gràcia,la Salut', city: 'Barcelona' },
    { name: 'Gràcia,la Vila de Gràcia', city: 'Barcelona' },
    { name: 'Gràcia,Vallcarca i els Penitents', city: 'Barcelona' },
    { name: 'Horta-Guinardó,Can Baró', city: 'Barcelona' },
    { name: 'Horta-Guinardó,el Baix Guinardó', city: 'Barcelona' },
    { name: 'Horta-Guinardó,el Carmel', city: 'Barcelona' },
    { name: 'Horta-Guinardó,el Guinardó', city: 'Barcelona' },
    { name: 'Horta-Guinardó,Horta', city: 'Barcelona' },
    { name: 'Horta-Guinardó,la Clota', city: 'Barcelona' },
    { name: `Horta-Guinardó,la Font d'en Fargues`, city: 'Barcelona' },
    { name: 'Horta-Guinardó,la Teixonera', city: 'Barcelona' },
    { name: `Horta-Guinardó,la Vall d'Hebron`, city: 'Barcelona' },
    { name: 'Horta-Guinardó,Montbau', city: 'Barcelona' },
    { name: 'Horta-Guinardó,Sant Genís dels Agudells', city: 'Barcelona' },
    { name: 'Les Corts,la Maternitat i Sant Ramon', city: 'Barcelona' },
    { name: 'Les Corts,les Corts', city: 'Barcelona' },
    { name: 'Les Corts,Pedralbes', city: 'Barcelona' },
    { name: 'Nou Barris,Can Peguera', city: 'Barcelona' },
    { name: 'Nou Barris,Canyelles', city: 'Barcelona' },
    { name: 'Nou Barris,Ciutat Meridiana', city: 'Barcelona' },
    { name: 'Nou Barris,el Turó de la Peira', city: 'Barcelona' },
    { name: 'Nou Barris,la Guineueta', city: 'Barcelona' },
    { name: 'Nou Barris,la Prosperitat', city: 'Barcelona' },
    { name: 'Nou Barris,la Trinitat Nova', city: 'Barcelona' },
    { name: 'Nou Barris,les Roquetes', city: 'Barcelona' },
    { name: 'Nou Barris,Porta', city: 'Barcelona' },
    { name: 'Nou Barris,Torre Baró', city: 'Barcelona' },
    { name: 'Nou Barris,Vallbona', city: 'Barcelona' },
    { name: 'Nou Barris,Verdun', city: 'Barcelona' },
    { name: 'Nou Barris,Vilapicina i la Torre Llobeta', city: 'Barcelona' },
    { name: 'Sant Andreu,Baró de Viver', city: 'Barcelona' },
    { name: 'Sant Andreu,el Bon Pastor', city: 'Barcelona' },
    { name: 'Sant Andreu,el Congrés i els Indians', city: 'Barcelona' },
    { name: 'Sant Andreu,la Sagrera', city: 'Barcelona' },
    { name: 'Sant Andreu,la Trinitat Vella', city: 'Barcelona' },
    { name: 'Sant Andreu,Navas', city: 'Barcelona' },
    { name: 'Sant Andreu,Sant Andreu', city: 'Barcelona' },
    { name: 'Sant Martí,Diagonal Mar i el Front Marítim del Poblenou', city: 'Barcelona' },
    { name: 'Sant Martí,el Besòs i el Maresme', city: 'Barcelona' },
    { name: `Sant Martí,el Camp de l'Arpa del Clot`, city: 'Barcelona' },
    { name: 'Sant Martí,el Clot', city: 'Barcelona' },
    { name: 'Sant Martí,el Parc i la Llacuna del Poblenou', city: 'Barcelona' },
    { name: 'Sant Martí,el Poblenou', city: 'Barcelona' },
    { name: 'Sant Martí,la Verneda i la Pau', city: 'Barcelona' },
    { name: 'Sant Martí,la Vila Olímpica del Poblenou', city: 'Barcelona' },
    { name: 'Sant Martí,Provençals del Poblenou', city: 'Barcelona' },
    { name: 'Sant Martí,Sant Martí de Provençals', city: 'Barcelona' },
    { name: 'Sants-Montjuic,el Poble Sec', city: 'Barcelona' },
    { name: 'Sants-Montjuic,Hostafrancs', city: 'Barcelona' },
    { name: 'Sants-Montjuic,la Bordeta', city: 'Barcelona' },
    { name: 'Sants-Montjuic,la Font de la Guatlla', city: 'Barcelona' },
    { name: 'Sants-Montjuic,la Marina del Prat Vermell', city: 'Barcelona' },
    { name: 'Sants-Montjuic,la Marina de Port', city: 'Barcelona' },
    { name: 'Sants-Montjuic,Sants', city: 'Barcelona' },
    { name: 'Sants-Montjuic,Sants - Badal', city: 'Barcelona' },
    { name: 'Sarrià-Sant Gervasi,el Putxet i el Farró', city: 'Barcelona' },
    { name: 'Sarrià-Sant Gervasi,les Tres Torres', city: 'Barcelona' },
    { name: 'Sarrià-Sant Gervasi,Sant Gervasi - Galvany', city: 'Barcelona' },
    { name: 'Sarrià-Sant Gervasi,Sant Gervasi - la Bonanova', city: 'Barcelona' },
    { name: 'Sarrià-Sant Gervasi,Sarrià', city: 'Barcelona' },
    { name: 'Sarrià-Sant Gervasi,Vallvidrera, el Tibidabo i les Planes', city: 'Barcelona' },

    { name: 'Santa Coloma de Gramenet,Centre', city: 'Barcelona Alrededores' },
    { name: 'Santa Coloma de Gramenet,Riera Alta-Llatí', city: 'Barcelona Alrededores' },
    { name: 'Santa Coloma de Gramenet,Fondo', city: 'Barcelona Alrededores' },
    { name: 'Santa Coloma de Gramenet,Santa Rosa-Can Mariné', city: 'Barcelona Alrededores' },
    { name: 'Santa Coloma de Gramenet,El Raval', city: 'Barcelona Alrededores' },
    { name: 'Santa Coloma de Gramenet,Riu', city: 'Barcelona Alrededores' },
    { name: 'Sant Adriá de Besós', city: 'Barcelona Alrededores' },
    { name: 'Sant Vicenç Dels Horts', city: 'Barcelona Alrededores' },
    { name: 'Sant Feliu de Llobregat', city: 'Barcelona Alrededores' },
    { name: 'Molins de Rei', city: 'Barcelona Alrededores' },
    { name: 'Sant Joan Despí', city: 'Barcelona Alrededores' },
    { name: 'Sant Just Desvern', city: 'Barcelona Alrededores' },
    { name: 'Esplugues', city: 'Barcelona Alrededores' },
    { name: 'Cornellá de Llobregat', city: 'Barcelona Alrededores' },
    { name: 'Sant Cugat del Vallés,Sant Cugat del Vallés', city: 'Barcelona Alrededores' },
    { name: 'Sant Cugat del Vallés,Valldoreix', city: 'Barcelona Alrededores' },
    { name: 'Sant Cugat del Vallés,Mirasol', city: 'Barcelona Alrededores' },
    { name: 'Sant Cugat del Vallés,Volpelleres', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Vilanova i la Geltrú,Barri de Mar,Ribes Roges', city: 'Barcelona Alrededores' },
    { name: `Garraf,Vilanova i la Geltrú,L'Aragai`, city: 'Barcelona Alrededores' },
    { name: `Garraf,Vilanova i la Geltrú,Centre Vila-La Geltrú`, city: 'Barcelona Alrededores' },
    { name: `Garraf,Vilanova i la Geltrú,Sant Joan - L'Aiguacuit`, city: 'Barcelona Alrededores' },
    { name: 'Garraf,Vilanova i la Geltrú,La Collada-Sis Camins-Nord', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Cubelles', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Sitges-Centre', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Sitges-Vinyet-Terramar-Can Pei-Girona', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Sitges-Vallpineda-Santa Bárbara-La Plana ', city: 'Barcelona Alrededores' },
    { name: `Garraf,Sitges-Ametller-Poble Sec-Ca L'Antoniet`, city: 'Barcelona Alrededores' },
    { name: 'Garraf,Sitges-San Sebastian-Aiguadolç', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Sitges-Els Molins-Observatorio-Pins Vens', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Sitges-Levantina-Montgavina-Quintmar', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Canyelles', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Sant Pere de Ribes', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Les Roquetes', city: 'Barcelona Alrededores' },
    { name: `Garraf,Mas d'En Serra- Els Cards`, city: 'Barcelona Alrededores' },
    { name: 'Garraf,Vallpineda-Rocamar', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Olivella', city: 'Barcelona Alrededores' },
    { name: 'Garraf,Castellet i la Gornal', city: 'Barcelona Alrededores' },
    { name: 'Viladecans', city: 'Barcelona Alrededores' },
    { name: 'Gavá', city: 'Barcelona Alrededores' },
    { name: 'Castelldefels', city: 'Barcelona Alrededores' },
    { name: 'Vilafranca del Penedès', city: 'Barcelona Alrededores' },
    { name: 'Badalona,Centre', city: 'Barcelona Alrededores' },
    { name: 'Badalona,Gorg-Progrés', city: 'Barcelona Alrededores' },
    { name: 'Badalona,Port', city: 'Barcelona Alrededores' },
    { name: 'Badalona,Montigalá-Sant Crist', city: 'Barcelona Alrededores' },
    { name: 'Badalona,La Salut', city: 'Barcelona Alrededores' },
    { name: 'Badalona,Llefiá-Sant Roc-Artigues', city: 'Barcelona Alrededores' },
    { name: 'Badalona,Bufalá', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Montgat', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Tiana', city: 'Barcelona Alrededores' },
    { name: 'Maresme,El Masnou', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Alella', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Premiá de Mar', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Premiá de Dalt', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Vilassar de Mar', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Vilassar de Dalt-Òrrius', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Cabrils', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Cabrera de Mar', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Argentona', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Dosrius', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Sant Andreu de Llavaneres', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Sant Vicenç de Montalt', city: 'Barcelona Alrededores' },
    { name: `Maresme,Caldes d' Estrac`, city: 'Barcelona Alrededores' },
    { name: 'Maresme,Arenys de Mar', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Arenys de Munt', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Canet de Mar', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Sant Pol de Mar', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Sant Cebriá-Sant Iscle', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Calella', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Pineda de Mar,Centre', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Pineda de Mar,Poblenou', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Pineda de Mar,Les Creus-Can Feliu de Merola-Can More-Pinemar-Can Cornet', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Santa Susanna', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Malgrat de Mar', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Palafolls', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Tordera', city: 'Barcelona Alrededores' },
    { name: 'Maresme,Mataró-Centre', city: 'Barcelona Alrededores' },
    { name: `Maresme,Mataró-Eixample-L'Havana- Rocafonda`, city: 'Barcelona Alrededores' },
    { name: 'Maresme,Mataró-Urbanizaciones', city: 'Barcelona Alrededores' },
    { name: `Maresme,Mataró-Plá d'En Boet`, city: 'Barcelona Alrededores' },
    { name: 'Sabadell,La Concordia-Can Rull', city: 'Barcelona Alrededores' },
    { name: `Sabadell,Ca N'Oriac- Can Puiggener`, city: 'Barcelona Alrededores' },
    { name: 'Sabadell,La Creu Alta', city: 'Barcelona Alrededores' },
    { name: 'Sabadell,Centre', city: 'Barcelona Alrededores' },
    { name: 'Sabadell,La Creu de Barberá-Avinguda-Eixample', city: 'Barcelona Alrededores' },
    { name: 'Sabadell,Can Gambús-Els Merinals-Can Feu-Gracia', city: 'Barcelona Alrededores' },
    { name: 'Terrassa,Centre', city: 'Barcelona Alrededores' },
    { name: 'Terrassa,Zona Esportiva-Sant Pere', city: 'Barcelona Alrededores' },
    { name: 'Terrassa,Vallparadís-Escoles', city: 'Barcelona Alrededores' },
    { name: 'Terrassa,Can Aurell-La Maurina-Roc Blanc', city: 'Barcelona Alrededores' },
    { name: 'Terrassa,Can Palet-Xúquer-Segle XX', city: 'Barcelona Alrededores' },
    { name: `Terrassa,Ca n'Anglada- Montserrat - Torresana`, city: 'Barcelona Alrededores' },
    { name: 'Manresa', city: 'Barcelona Alrededores' },
    { name: 'Granollers', city: 'Barcelona Alrededores' },
    { name: 'Vic', city: 'Barcelona Alrededores' },
    { name: 'Cerdanyola del Vallés', city: 'Barcelona Alrededores' },

    { name: 'Papa Luna', city: 'Benicarló' },
    { name: 'Puerto Playa', city: 'Benicarló' },
    { name: 'Zona Pueblo', city: 'Benicarló' },

    { name: 'Betanzos', city: 'Betanzos' },

    { name: 'Casco Viejo', city: 'Bilbao' },
    { name: 'Ibaiondo', city: 'Bilbao' },
    { name: 'Begoña-Santutxu', city: 'Bilbao' },
    { name: 'Otxarkoaga - Txurdinaga', city: 'Bilbao' },
    { name: 'Uribarri', city: 'Bilbao' },
    { name: 'Deusto,San Pedro de Deusto-Arangoit', city: 'Bilbao' },
    { name: 'Deusto,La Ribera-Ibarrekolanda', city: 'Bilbao' },
    { name: 'Abando - Albia,Abandoibarra-Guggenheim', city: 'Bilbao' },
    { name: 'Abando - Albia,Ensanche-Moyua', city: 'Bilbao' },
    { name: 'Abando - Albia,Zabalburu-Diputación', city: 'Bilbao' },
    { name: 'Abando - Albia,Plaza Circular', city: 'Bilbao' },
    { name: 'Abando - Albia,Albia', city: 'Bilbao' },
    { name: 'Basurto - Zorroza,Zorrotza-Olabeaga', city: 'Bilbao' },
    { name: 'Basurto - Zorroza,Altamira- Monte Caramelo', city: 'Bilbao' },
    { name: 'Basurto - Zorroza,Basurtu', city: 'Bilbao' },
    { name: 'Rekalde,Ametzola', city: 'Bilbao' },
    { name: 'Rekalde,Irala', city: 'Bilbao' },
    { name: 'Rekalde,Artatzu-Larraskitu-Uretamendi-Betolaza-Peñaskal', city: 'Bilbao' },
    { name: 'Rekalde,Rekalde Centro', city: 'Bilbao' },
    { name: 'San Adrián-La Peña', city: 'Bilbao' },
    { name: 'San Ignacio', city: 'Bilbao' },

    { name: 'Centro', city: 'Burgos' },
    { name: 'Casco Antiguo', city: 'Burgos' },
    { name: 'San Pedro de la Fuente', city: 'Burgos' },
    { name: 'Fuentecillas', city: 'Burgos' },
    { name: 'Illera', city: 'Burgos' },
    { name: 'Plantío-Al Campo', city: 'Burgos' },
    { name: 'Capiscol-Gamonal', city: 'Burgos' },

    { name: 'Centro', city: 'Cáceres' },
    { name: 'Casco Antiguo', city: 'Cáceres' },
    { name: 'Oeste-Nuevo Oeste', city: 'Cáceres' },
    { name: 'Sur', city: 'Cáceres' },
    { name: 'Montesol-Mejostilla', city: 'Cáceres' },
    { name: 'Aguas Vivas - La Zambomba', city: 'Cáceres' },

    { name: 'Centro Histórico-Plaza España', city: 'Cádiz' },
    { name: 'Ayuntamiento-Catedral', city: 'Cádiz' },
    { name: 'Mentidero-Teatro Falla-Alameda', city: 'Cádiz' },
    { name: 'La Caleta-La Viña', city: 'Cádiz' },
    { name: 'La Paz-Segunda Aguada-Loreto', city: 'Cádiz' },
    { name: 'San José-Varela', city: 'Cádiz' },
    { name: 'Bahía Blanca', city: 'Cádiz' },
    { name: 'Playa Victoria', city: 'Cádiz' },
    { name: 'Playa Santa María del Mar', city: 'Cádiz' },

    { name: 'Casco Antiguo', city: 'Cartagena' },
    { name: 'Alameda', city: 'Cartagena' },
    { name: 'Ensanche', city: 'Cartagena' },
    { name: 'San Ginés-Virgen de la Caridad', city: 'Cartagena' },
    { name: 'Ciudad Jardín ', city: 'Cartagena' },
    { name: 'San Antón', city: 'Cartagena' },
    { name: 'Los Barreros-Cuatro Santos', city: 'Cartagena' },
    { name: 'Peral-La Vereda', city: 'Cartagena' },

    { name: 'Centro,Parque Ribalta-Plaza de Toros', city: 'Castellón de la Plana' },
    { name: 'Centro,Casco Histórico', city: 'Castellón de la Plana' },
    { name: 'Centro,Zona Hospital-Plaza de Real', city: 'Castellón de la Plana' },
    { name: 'Sur,Ensanche-Parque Oeste', city: 'Castellón de la Plana' },
    { name: 'Sur,Avenida de Valencia-Avenida de Casalduch', city: 'Castellón de la Plana' },
    { name: 'Sur,Zona Ensanche-Río Júcar', city: 'Castellón de la Plana' },
    { name: 'Sur,Zona Ensanche-Santa Rosa', city: 'Castellón de la Plana' },
    { name: 'Oeste,Mestrets', city: 'Castellón de la Plana' },
    { name: 'Oeste,Estación-Universidad', city: 'Castellón de la Plana' },
    { name: 'Oeste,Ciutat del Transport-La Salera', city: 'Castellón de la Plana' },
    { name: 'Norte,Estadio Castalia', city: 'Castellón de la Plana' },
    { name: 'Norte,Plaza Donoso Cortés-Avenida Magdalena', city: 'Castellón de la Plana' },
    { name: 'Norte,Plaza Illes Columbretes', city: 'Castellón de la Plana' },
    { name: 'Norte,Pau Lledó', city: 'Castellón de la Plana' },
    { name: 'Este,Rafalaena', city: 'Castellón de la Plana' },
    { name: 'Este,Zona Avenida del Mar', city: 'Castellón de la Plana' },
    { name: 'Este,Parque Geológo José Royo Gómez', city: 'Castellón de la Plana' },

    { name: 'La Morería', city: 'Ciudad Real' },
    { name: 'Centro-Plaza Mayor', city: 'Ciudad Real' },
    { name: 'Plaza de Toros', city: 'Ciudad Real' },
    { name: 'El Perchel', city: 'Ciudad Real' },
    { name: 'El Torreón-Los Ángeles-El Pilar', city: 'Ciudad Real' },
    { name: 'Nuevo parque', city: 'Ciudad Real' },
    { name: 'Larache', city: 'Ciudad Real' },
    { name: 'Nuevo Hospital', city: 'Ciudad Real' },
    { name: 'Los Rosales', city: 'Ciudad Real' },
    { name: 'Ciudad Jardín', city: 'Ciudad Real' },
    { name: 'Santa María-Pio XII', city: 'Ciudad Real' },
    { name: 'La Guija', city: 'Ciudad Real' },

    { name: 'Centro-Casco histórico,Centro', city: 'Córdoba' },
    { name: 'Centro-Casco histórico,Juderia-San Basilio', city: 'Córdoba' },
    { name: 'Centro-Casco histórico,Casco Histórico - Corredera - Ribera', city: 'Córdoba' },
    { name: 'Centro-Casco histórico,Casco Histórico - Ollerías - Marrubial', city: 'Córdoba' },
    { name: 'Centro-Casco histórico,San Cayetano', city: 'Córdoba' },
    { name: 'Centro-Casco histórico,El Vial - Ronda de Tejares', city: 'Córdoba' },
    { name: 'Santa Rosa - Valdeolleros,Huerta de la Reina', city: 'Córdoba' },
    { name: 'Santa Rosa - Valdeolleros,Santa Rosa - San José', city: 'Córdoba' },
    { name: 'Santa Rosa - Valdeolleros,Valdeolleros - Zumbacón - Camping', city: 'Córdoba' },
    { name: 'Ciudad Jardín', city: 'Córdoba' },
    { name: 'Zoco-Poniente-Vistalegre', city: 'Córdoba' },
    { name: 'El Higuerón', city: 'Córdoba' },
    { name: 'Sector Sur-Santa Cruz', city: 'Córdoba' },
    { name: 'Fuensanta-Arcángel', city: 'Córdoba' },
    { name: 'Levante-Lepanto-Fátima,Levante', city: 'Córdoba' },
    { name: 'Levante-Lepanto-Fátima,La Viñuela', city: 'Córdoba' },
    { name: 'Levante-Lepanto-Fátima,El Cairo', city: 'Córdoba' },
    { name: 'Levante-Lepanto-Fátima,Fátima - Campiñuela', city: 'Córdoba' },
    { name: 'Levante-Lepanto-Fátima,Alcolea', city: 'Córdoba' },
    { name: 'Noreña-Figueroa,Miralbaida - Parque Azahara', city: 'Córdoba' },
    { name: 'Noreña-Figueroa,Noreña - Turruñuelos', city: 'Córdoba' },
    { name: 'Noreña-Figueroa,Carretera Trassierra - Colonia de la Paz', city: 'Córdoba' },
    { name: 'Noreña-Figueroa,Tablero', city: 'Córdoba' },
    { name: 'Brillante - Trassierra - Naranjo,Naranjo - Mirabueno', city: 'Córdoba' },
    { name: 'Brillante - Trassierra - Naranjo,Brillante', city: 'Córdoba' },
    { name: 'Brillante - Trassierra - Naranjo,Paraíso Arenal - La Colina', city: 'Córdoba' },
    { name: 'Brillante - Trassierra - Naranjo,Trassierra - Las Jaras', city: 'Córdoba' },

    { name: 'Cuenca Centro', city: 'Cuenca' },

    { name: 'Don Benito', city: 'Denia' },
    { name: 'El Puerto', city: 'Denia' },
    { name: 'Saladar', city: 'Denia' },
    { name: 'Centro Urbano', city: 'Denia' },
    { name: `Las Marinas,L'Almadrava- L'Estanyó`, city: 'Denia' },
    { name: 'Las Marinas,El Palmar-Los Molinos', city: 'Denia' },
    { name: 'Las Marinas,Les Bovetes-La Felicidad', city: 'Denia' },
    { name: 'Las Marinas,Les Bassetes-El Marjal', city: 'Denia' },
    { name: 'El Montgó', city: 'Denia' },

    { name: 'Don Benito', city: 'Don Benito' },

    { name: 'Ejido Centro', city: 'El Ejido' },
    { name: 'Ejido Norte', city: 'El Ejido' },
    { name: 'Plaza de la Luz', city: 'El Ejido' },
    { name: 'Ejido Sur', city: 'El Ejido' },
    { name: 'Pabellón-Estación-Corte Inglés', city: 'El Ejido' },
    { name: 'Santo Domingo', city: 'El Ejido' },

    { name: 'Centro', city: 'Elche' },
    { name: 'Pont Nou-Corazón de Jesús', city: 'Elche' },
    { name: 'Reina Victoria-Miguel Hernández', city: 'Elche' },
    { name: 'Plaza Crevillente-Juzgados', city: 'Elche' },
    { name: 'Sector V- El Canal', city: 'Elche' },
    { name: 'Portes Encarnades-Torretas-Portalada', city: 'Elche' },
    { name: 'Altabix', city: 'Elche' },
    { name: 'Sant Antón-Ciudad Jardín', city: 'Elche' },
    { name: 'Travalón', city: 'Elche' },
    { name: 'Zona Deportiva-Nuevo Altabix', city: 'Elche' },
    { name: 'Carrús Oeste', city: 'Elche' },
    { name: 'Carrús Este', city: 'Elche' },
    { name: 'Los Magros-Casablanca', city: 'Elche' },
    { name: 'Zona Universidad', city: 'Elche' },
    { name: 'Toscar', city: 'Elche' },
    { name: 'San Crispín', city: 'Elche' },

    { name: 'Ferrol', city: 'Ferrol' },

    { name: 'Centro', city: 'Gijón' },
    { name: 'Llano', city: 'Gijón' },
    { name: 'Sur', city: 'Gijón' },
    { name: 'Este', city: 'Gijón' },
    { name: 'Oeste', city: 'Gijón' },

    { name: 'Migdia Casernes', city: 'Girona' },
    { name: 'Eixample', city: 'Girona' },
    { name: 'Barri Vell', city: 'Girona' },
    { name: 'Sant Narcís', city: 'Girona' },
    { name: 'Santa Eugenia', city: 'Girona' },
    { name: 'Montilivi-Pericot', city: 'Girona' },
    { name: 'Fontajau-Domeny-Montjuic', city: 'Girona' },
    { name: 'Palau', city: 'Girona' },
    { name: 'Carme-Vistalegre', city: 'Girona' },

    { name: `Platja de Aro,Port d' Aro`, city: 'Girona Costa Brava' },
    { name: 'Platja de Aro,Platja Llarga', city: 'Girona Costa Brava' },
    { name: 'Platja de Aro,Centre Estanys', city: 'Girona Costa Brava' },
    { name: 'Platja de Aro,Fenals', city: 'Girona Costa Brava' },
    { name: 'Platja de Aro,Cavall Bernat-Cala Rovira', city: 'Girona Costa Brava' },
    { name: 'Platja de Aro,Los Pinos Politur', city: 'Girona Costa Brava' },
    { name: 'Sant Feliú de Guíxols,Barri de Tudela', city: 'Girona Costa Brava' },
    { name: 'Sant Feliú de Guíxols,Sant Pol-Volta de Ametller', city: 'Girona Costa Brava' },
    {
        name: `Sant Feliú de Guíxols,L'Eixample`, city: 'Girona Costa Brava'
    },
    { name: 'Sant Feliú de Guíxols,Centre', city: 'Girona Costa Brava' },
    { name: 'Sant Feliú de Guíxols,Vilartagues i Tueda de Dalt', city: 'Girona Costa Brava' },
    { name: 'Tossa de Mar ', city: 'Girona Costa Brava' },
    { name: 'Blanes,Centre', city: 'Girona Costa Brava' },
    { name: 'Blanes,Els Pavos', city: 'Girona Costa Brava' },
    { name: 'Blanes,Els Pins', city: 'Girona Costa Brava' },
    { name: 'Blanes,La Plantera', city: 'Girona Costa Brava' },
    { name: 'Blanes,Semicentre', city: 'Girona Costa Brava' },
    { name: 'Blanes,Mont Ferrant-Sant Joan', city: 'Girona Costa Brava' },
    { name: 'Blanes,Cala Sant Francesc-Santa Cristina', city: 'Girona Costa Brava' },
    { name: 'Lloret de Mar,Casc Antic', city: 'Girona Costa Brava' },
    { name: 'Lloret de Mar,Fenals', city: 'Girona Costa Brava' },
    { name: 'Lloret de Mar,Santa Clotilde', city: 'Girona Costa Brava' },
    { name: 'Lloret de Mar,Can Sabata-Mas Baell ', city: 'Girona Costa Brava' },
    { name: 'Lloret de Mar,Canyelles-Montgoda', city: 'Girona Costa Brava' },
    { name: 'Lloret de Mar,Roca Grossa', city: 'Girona Costa Brava' },
    { name: 'Palafrugell,Centre', city: 'Girona Costa Brava' },
    { name: 'Palafrugell,Molí de Vent-La Sauleda-Santa Margarida', city: 'Girona Costa Brava' },
    { name: 'Palafrugell,Piverd-La Roella-Bruguerol', city: 'Girona Costa Brava' },
    { name: 'Palafrugell,La Punxa-Bóbila Nova-Mas Mascort', city: 'Girona Costa Brava' },
    { name: 'Roses,Centre', city: 'Girona Costa Brava' },
    { name: 'Roses,Salatar', city: 'Girona Costa Brava' },
    { name: 'Roses,Santa Margarida', city: 'Girona Costa Brava' },
    { name: 'Roses,Port Esportiu-Puig Rom-Canyelles', city: 'Girona Costa Brava' },
    { name: 'Roses,El Grecs-Mas Oliva', city: 'Girona Costa Brava' },
    { name: 'Roses,Nord', city: 'Girona Costa Brava' },
    { name: 'Empuriabrava', city: 'Girona Costa Brava' },
    { name: 'Sant Celoni', city: 'Girona Costa Brava' },
    { name: 'Figueres,Centre', city: 'Girona Costa Brava' },
    { name: 'Figueres,Creu de la Ma-Rally Sur', city: 'Girona Costa Brava' },
    { name: `Figueres,L'Eixample`, city: 'Girona Costa Brava' },
    { name: `Figueres,Poble Nou-L'Oliva Gran`, city: 'Girona Costa Brava' },
    { name: `Figueres,Parc Bosc Castell`, city: 'Girona Costa Brava' },

    { name: 'Centro,Gran Vía', city: 'Granada' },
    { name: 'Centro,Gran Capitán', city: 'Granada' },
    { name: 'Centro,Jardín Botánico', city: 'Granada' },
    { name: 'Centro,Recogidas', city: 'Granada' },
    { name: 'Centro,Catedral', city: 'Granada' },
    { name: 'Los Pajaritos-Plaza de Toros', city: 'Granada' },
    { name: 'San Francisco Javier-Eguaras', city: 'Granada' },
    { name: 'San Ildefonso', city: 'Granada' },
    { name: 'Barrio de los Periodistas', city: 'Granada' },
    { name: 'La Chana', city: 'Granada' },
    { name: 'Ronda-Arabial', city: 'Granada' },
    { name: 'Cartuja-Barriala La Paz', city: 'Granada' },
    { name: 'Albaicín', city: 'Granada' },
    { name: 'Realejo', city: 'Granada' },
    { name: 'Figares', city: 'Granada' },
    { name: 'Cervantes-Palacio de Deportes', city: 'Granada' },
    { name: 'Bola de Oro', city: 'Granada' },
    { name: 'Zaidín', city: 'Granada' },

    { name: 'Casco Histórico', city: 'Guadalajara' },
    { name: 'Constitución-El Balconsillo', city: 'Guadalajara' },
    { name: 'Plan Sur-Amistad', city: 'Guadalajara' },
    { name: 'San Roque', city: 'Guadalajara' },
    { name: 'Los Valles-San Vázquez-El Fuerte', city: 'Guadalajara' },
    { name: 'Alamín', city: 'Guadalajara' },
    { name: 'Aguas Vivas', city: 'Guadalajara' },
    { name: 'Las Lomas', city: 'Guadalajara' },
    { name: 'Las Cañas', city: 'Guadalajara' },
    { name: 'Estación-Manantiales', city: 'Guadalajara' },

    { name: 'Huesca', city: 'Huelva' },
    { name: 'Centro', city: 'Huelva' },
    { name: 'Las Torres-Guadalupe', city: 'Huelva' },
    { name: 'El Conquero', city: 'Huelva' },
    { name: 'Isla Chica', city: 'Huelva' },

    { name: 'Sant Joan de Labritja-Portinatx', city: 'Ibiza' },
    { name: 'Sant Antoni de Portmany', city: 'Ibiza' },
    { name: 'Sant Josep de Sa Talaia,Sant Agustín-Cala de Bou', city: 'Ibiza' },
    { name: 'Sant Josep de Sa Talaia,Cala Vedella-Cala Tarida-Cala Conta', city: 'Ibiza' },
    { name: 'Sant Josep de Sa Talaia,Sant Josep de Sa Talaia', city: 'Ibiza' },
    { name: 'Sant Josep de Sa Talaia,Es Cubells', city: 'Ibiza' },
    { name: 'Sant Josep de Sa Talaia,Sant Jordi de Ses Salines', city: 'Ibiza' },
    { name: 'Santa Eulalia del Río,Puig Den Valls', city: 'Ibiza' },
    { name: 'Santa Eulalia del Río,Santa Gertrudis', city: 'Ibiza' },
    { name: 'Santa Eulalia del Río,Jesús/Nuestra Señora de Jesús', city: 'Ibiza' },
    { name: 'Santa Eulalia del Río,Santa Eulalia del Río', city: 'Ibiza' },
    { name: 'Santa Eulalia del Río,San Carlos', city: 'Ibiza' },
    { name: 'Eivissa,Dalt Vila-La Marina', city: 'Ibiza' },
    { name: `Eivissa,Figueretes-Platja d'En Bossa`, city: 'Ibiza' },
    { name: `Eivissa,Centro-S'Eixample - Can Misses`, city: 'Ibiza' },
    { name: 'Eivissa,Marina Botafonc-Talamanca', city: 'Ibiza' },

    { name: 'Irún', city: 'Irún' },

    { name: 'Vegueta, Cono Sur y Tafira', city: 'Jaén' },
    { name: 'San Bartolomé-Millán de Priego', city: 'Jaén' },
    { name: 'San Felipe-El Almendral-La Merced', city: 'Jaén' },
    { name: 'San Ildefonso-Catedral', city: 'Jaén' },
    { name: 'Belén-San Roque', city: 'Jaén' },
    { name: 'Santa Isabel', city: 'Jaén' },
    { name: 'Hospital', city: 'Jaén' },

    { name: 'Peñamefécit-Avenida Barcelona', city: 'Jávea' },
    { name: 'Centro', city: 'Jávea' },
    { name: 'Puerto', city: 'Jávea' },
    { name: 'Montañar-El Arenal', city: 'Jávea' },
    { name: 'Cap Martí-Pinomar', city: 'Jávea' },
    { name: 'Portichol-Balcón al Mar', city: 'Jávea' },
    { name: 'Partida Tosal-Zona dels Castellans', city: 'Jávea' },
    { name: 'La Granadella-Costa Nova', city: 'Jávea' },

    { name: 'Partida Comunes-Adsubia', city: 'Jerez de la Frontera' },
    { name: 'Centro', city: 'Jerez de la Frontera' },
    { name: 'Guadajabeque-Puertas del Sur', city: 'Jerez de la Frontera' },
    { name: 'Santiago-Coronación', city: 'Jerez de la Frontera' },
    { name: 'Jerez Oeste', city: 'Jerez de la Frontera' },
    { name: 'Avenida-Divina Pastora-Plaza de Toros', city: 'Jerez de la Frontera' },
    { name: 'Jerez Norte-Montealto-Pozoalbero', city: 'Jerez de la Frontera' },
    { name: 'Chapin-Campus Universitario-Navinco', city: 'Jerez de la Frontera' },
    { name: 'El Rocío-La Milagrosa', city: 'Jerez de la Frontera' },
    { name: 'El Retiro-Parque Atlántico-Parque Este', city: 'Jerez de la Frontera' },

    { name: 'Centro,Alcaravaneras', city: 'Las Palmas de Gran Canaria' },
    { name: 'Centro,Ciudad Jardín', city: 'Las Palmas de Gran Canaria' },
    { name: 'Centro,Arenales - Lugo - Avda Marítima', city: 'Las Palmas de Gran Canaria' },
    { name: 'Mapa de Puerto - Canteras,Guanarteme', city: 'Las Palmas de Gran Canaria' },
    { name: 'Mapa de Puerto - Canteras,Santa Catalina', city: 'Las Palmas de Gran Canaria' },
    { name: 'Mapa de Puerto - Canteras,La Isleta', city: 'Las Palmas de Gran Canaria' },
    { name: 'Ciudad Alta,Siete Palmas', city: 'Las Palmas de Gran Canaria' },
    { name: 'Ciudad Alta,Schamann-Rehoyas', city: 'Las Palmas de Gran Canaria' },
    { name: 'Ciudad Alta,Escaleritas-La Feria', city: 'Las Palmas de Gran Canaria' },
    { name: 'Ciudad Alta,Altavista-Don Zoilo', city: 'Las Palmas de Gran Canaria' },
    { name: 'Ciudad Alta,Miller', city: 'Las Palmas de Gran Canaria' },
    { name: 'Ciudad Alta,Los Tarahales-La Paterna', city: 'Las Palmas de Gran Canaria' },
    { name: 'Ciudad Alta,La Minilla', city: 'Las Palmas de Gran Canaria' },
    { name: 'Ciudad Alta,Negrín', city: 'Las Palmas de Gran Canaria' },
    { name: 'Tamareceite-San Lorenzo', city: 'Las Palmas de Gran Canaria' },
    { name: 'Tafira', city: 'Las Palmas de Gran Canaria' },
    { name: 'Carretera del Centro - Cono sur', city: 'Las Palmas de Gran Canaria' },

    { name: 'Centro Ciudad', city: 'León' },
    { name: 'Casco Antiguo', city: 'León' },
    { name: 'San Esteban', city: 'León' },
    { name: 'Las Eras de Renueva', city: 'León' },
    { name: 'Crucero-Pinilla', city: 'León' },
    { name: 'La Vega-Oteruelo', city: 'León' },
    { name: 'La Chantría-La Lastra', city: 'León' },
    { name: 'El Ejido-Santa Ana', city: 'León' },
    { name: 'San Mamés-La Palomera', city: 'León' },

    { name: 'Centre Historic', city: 'Lleida' },
    { name: 'Principe de Viana-Clot', city: 'Lleida' },
    { name: `Camp d'Esports - Joc de Bola`, city: 'Lleida' },
    { name: 'Mariola', city: 'Lleida' },
    { name: 'Universitat', city: 'Lleida' },
    { name: 'Rambla de Ferrán,Pardinyes', city: 'Lleida' },
    { name: 'Cappont', city: 'Lleida' },
    { name: 'Balàfia', city: 'Lleida' },

    { name: 'Casco Histórico', city: 'Logroño' },
    { name: 'Oeste', city: 'Logroño' },
    { name: 'Centro', city: 'Logroño' },
    { name: 'Residencia', city: 'Logroño' },
    { name: 'Universidad-Los Lirios', city: 'Logroño' },
    { name: 'El Campillo-Polígono Cantabria', city: 'Logroño' },
    { name: 'Portillejo-Valdegastea', city: 'Logroño' },
    { name: 'San Adrián-La Cava', city: 'Logroño' },
    { name: 'Cascajos- Piqueras', city: 'Logroño' },

    { name: 'Plaza Maior', city: 'Lugo' },
    { name: 'Catasol-Sanxillao', city: 'Lugo' },
    { name: 'Carme-Fingoi', city: 'Lugo' },
    { name: 'La Milagrosa-Piringalla', city: 'Lugo' },
    { name: 'Avenida de A Coruña', city: 'Lugo' },

    { name: 'Arganzuela,Acacias', city: 'Madrid' },
    { name: 'Arganzuela,Atocha-Palos de Moguer', city: 'Madrid' },
    { name: 'Arganzuela,Chopera', city: 'Madrid' },
    { name: 'Arganzuela,Delicias', city: 'Madrid' },
    { name: 'Arganzuela,Imperial', city: 'Madrid' },
    { name: 'Arganzuela,Legazpi', city: 'Madrid' },
    { name: 'Barajas', city: 'Madrid' },
    { name: 'Carabanchel,Abrantes', city: 'Madrid' },
    { name: 'Carabanchel,Buenavista', city: 'Madrid' },
    { name: 'Carabanchel,Comillas', city: 'Madrid' },
    { name: 'Carabanchel,Opañel', city: 'Madrid' },
    { name: 'Carabanchel,Puerta Bonita', city: 'Madrid' },
    { name: 'Carabanchel,San Isidro', city: 'Madrid' },
    { name: 'Carabanchel,Vista Alegre', city: 'Madrid' },
    { name: 'Carabanchel,Pau de Carabanchel', city: 'Madrid' },
    { name: 'Centro,Cortes-Huertas', city: 'Madrid' },
    { name: 'Centro,Embajadores-Lavapiés', city: 'Madrid' },
    { name: 'Centro,Justicia-Chueca', city: 'Madrid' },
    { name: 'Centro,Palacio', city: 'Madrid' },
    { name: 'Centro,Sol', city: 'Madrid' },
    { name: 'Centro,Universidad-Malasaña', city: 'Madrid' },
    { name: 'Chamartín,Castilla', city: 'Madrid' },
    { name: 'Chamartín,Ciudad Jardín', city: 'Madrid' },
    { name: 'Chamartín,El Viso', city: 'Madrid' },
    { name: 'Chamartín,Hispanoamérica-Bernabéu', city: 'Madrid' },
    { name: 'Chamartín,Nueva España', city: 'Madrid' },
    { name: 'Chamartín,Prosperidad', city: 'Madrid' },
    { name: 'Chamberí,Almagro', city: 'Madrid' },
    { name: 'Chamberí,Arapiles', city: 'Madrid' },
    { name: 'Chamberí,Gaztambide', city: 'Madrid' },
    { name: 'Chamberí,Rios Rosas-Nuevos Ministerios', city: 'Madrid' },
    { name: 'Chamberí,Trafalgar', city: 'Madrid' },
    { name: 'Chamberí,Vallehermoso', city: 'Madrid' },
    { name: 'Ciudad Lineal,Atalaya', city: 'Madrid' },
    { name: 'Ciudad Lineal,Colina', city: 'Madrid' },
    { name: 'Ciudad Lineal,Concepción', city: 'Madrid' },
    { name: 'Ciudad Lineal,Costillares', city: 'Madrid' },
    { name: 'Ciudad Lineal,Pueblo Nuevo', city: 'Madrid' },
    { name: 'Ciudad Lineal,Quintana', city: 'Madrid' },
    { name: 'Ciudad Lineal,San Juan Bautista', city: 'Madrid' },
    { name: 'Ciudad Lineal,San Pascual', city: 'Madrid' },
    { name: 'Ciudad Lineal,Ventas', city: 'Madrid' },
    { name: 'Fuencarral - El Pardo,El Goloso-Montecarmelo', city: 'Madrid' },
    { name: 'Fuencarral - El Pardo,El Pardo', city: 'Madrid' },
    { name: 'Fuencarral - El Pardo,Fuentelareina', city: 'Madrid' },
    { name: 'Fuencarral - El Pardo,La Paz', city: 'Madrid' },
    { name: 'Fuencarral - El Pardo,Mirasierra', city: 'Madrid' },
    { name: 'Fuencarral - El Pardo,Peñagrande', city: 'Madrid' },
    { name: 'Fuencarral - El Pardo,Pilar', city: 'Madrid' },
    { name: 'Fuencarral - El Pardo,Valverde-Tres Olivos', city: 'Madrid' },
    { name: 'Fuencarral - El Pardo,Arroyo del Fresno', city: 'Madrid' },
    { name: 'Hortaleza,Apostol Santiago', city: 'Madrid' },
    { name: 'Hortaleza,Canillas', city: 'Madrid' },
    { name: 'Hortaleza,Palomas', city: 'Madrid' },
    { name: 'Hortaleza,Pinar del Rey', city: 'Madrid' },
    { name: 'Hortaleza,Piovera-Conde Orgaz', city: 'Madrid' },
    { name: 'Hortaleza,Valdefuentes-Valdedebas', city: 'Madrid' },
    { name: 'Hortaleza,Sanchinarro', city: 'Madrid' },
    { name: 'Hortaleza,Virgen del Cotijo-Manoteras', city: 'Madrid' },
    { name: 'Latina,Águilas', city: 'Madrid' },
    { name: 'Latina,Aluche', city: 'Madrid' },
    { name: 'Latina,Campamento', city: 'Madrid' },
    { name: 'Latina,Cármenes', city: 'Madrid' },
    { name: 'Latina,Lucero', city: 'Madrid' },
    { name: 'Latina,Puerta del Angel', city: 'Madrid' },
    { name: 'Moncloa - Aravaca,Aravaca', city: 'Madrid' },
    { name: 'Moncloa - Aravaca,Argüelles', city: 'Madrid' },
    { name: 'Moncloa - Aravaca,Casa de Campo', city: 'Madrid' },
    { name: 'Moncloa - Aravaca,Ciudad Universitaria', city: 'Madrid' },
    { name: 'Moncloa - Aravaca,El Plantío', city: 'Madrid' },
    { name: 'Moncloa - Aravaca,Valdemarín', city: 'Madrid' },
    { name: 'Moncloa - Aravaca,Valdezarza', city: 'Madrid' },
    { name: 'Moratalaz', city: 'Madrid' },
    { name: 'Puente de Vallecas,Entrevías', city: 'Madrid' },
    { name: 'Puente de Vallecas,Numancia', city: 'Madrid' },
    { name: 'Puente de Vallecas,Palomeras Bajas', city: 'Madrid' },
    { name: 'Puente de Vallecas,Palomeras Sureste', city: 'Madrid' },
    { name: 'Puente de Vallecas,Portazgo', city: 'Madrid' },
    { name: 'Puente de Vallecas,San Diego', city: 'Madrid' },
    { name: 'Retiro,Adelfas', city: 'Madrid' },
    { name: 'Retiro,Estrella', city: 'Madrid' },
    { name: 'Retiro,Ibiza', city: 'Madrid' },
    { name: 'Retiro,Jerónimos', city: 'Madrid' },
    { name: 'Retiro,Niño Jesús', city: 'Madrid' },
    { name: 'Retiro,Pacífico', city: 'Madrid' },
    { name: 'Salamanca,Castellana', city: 'Madrid' },
    { name: 'Salamanca,Fuente del Berro', city: 'Madrid' },
    { name: 'Salamanca,Goya', city: 'Madrid' },
    { name: 'Salamanca,Guindalera', city: 'Madrid' },
    { name: 'Salamanca,Lista', city: 'Madrid' },
    { name: 'Salamanca,Recoletos', city: 'Madrid' },
    { name: 'San Blas-Canillejas,Amposta', city: 'Madrid' },
    { name: 'San Blas-Canillejas,Arcos', city: 'Madrid' },
    { name: 'San Blas-Canillejas,Canillejas', city: 'Madrid' },
    { name: 'San Blas-Canillejas,Hellín', city: 'Madrid' },
    { name: 'San Blas-Canillejas,Rejas', city: 'Madrid' },
    { name: 'San Blas-Canillejas,Rosas', city: 'Madrid' },
    { name: 'San Blas-Canillejas,Salvador', city: 'Madrid' },
    { name: 'San Blas-Canillejas,Simancas', city: 'Madrid' },
    { name: 'Tetuán,Almenara-Ventilla', city: 'Madrid' },
    { name: 'Tetuán,Bellas Vistas', city: 'Madrid' },
    { name: 'Tetuán,Berruguete', city: 'Madrid' },
    { name: 'Tetuán,Castillejos-Cuzco', city: 'Madrid' },
    { name: 'Tetuán,Cuatro Caminos', city: 'Madrid' },
    { name: 'Tetuán,Valdeacederas', city: 'Madrid' },
    { name: 'Usera,Almendrales', city: 'Madrid' },
    { name: 'Usera,Moscardó', city: 'Madrid' },
    { name: 'Usera,Orcasitas', city: 'Madrid' },
    { name: 'Usera,Orcasur-12 de Octubre', city: 'Madrid' },
    { name: 'Usera,Pradolongo', city: 'Madrid' },
    { name: 'Usera,San Fermín', city: 'Madrid' },
    { name: 'Usera,Zofío', city: 'Madrid' },
    { name: 'Vicálvaro,Ambroz', city: 'Madrid' },
    { name: 'Vicálvaro,Casco Histórico de Vicálvaro', city: 'Madrid' },
    { name: 'Vicálvaro,Valdebernardo-Valderribas', city: 'Madrid' },
    { name: 'Vicálvaro,El Cañavera-Los Berrocales', city: 'Madrid' },
    { name: 'Villa de Vallecas,Casco Histórico de Vallecas', city: 'Madrid' },
    { name: 'Villa de Vallecas,Ensanche de Vallecas-La Gavia', city: 'Madrid' },
    { name: 'Villa de Vallecas,Santa Eugenia', city: 'Madrid' },
    { name: 'Villaverde,Butarque', city: 'Madrid' },
    { name: 'Villaverde,Los Angeles', city: 'Madrid' },
    { name: 'Villaverde,Los Rosales', city: 'Madrid' },
    { name: 'Villaverde,San Andrés', city: 'Madrid' },
    { name: 'Villaverde,San Cristobal', city: 'Madrid' },

    { name: 'Bailen-Miraflores', city: 'Madrid Alrededores' },
    { name: 'Aranjuez', city: 'Madrid Alrededores' },
    { name: 'Valdemoro', city: 'Madrid Alrededores' },
    { name: 'Parla', city: 'Madrid Alrededores' },
    { name: 'Collado de Villalba', city: 'Madrid Alrededores' },
    { name: 'Alcalá de Henares', city: 'Madrid Alrededores' },
    { name: 'Torrejón del Ardoz', city: 'Madrid Alrededores' },
    { name: 'Arganda del Rey', city: 'Madrid Alrededores' },
    { name: 'Móstoles', city: 'Madrid Alrededores' },
    { name: 'Villaviciosa de Odón', city: 'Madrid Alrededores' },
    { name: 'San Sebastián de los Reyes', city: 'Madrid Alrededores' },
    { name: 'Alcobendas', city: 'Madrid Alrededores' },
    { name: 'Las Rozas de Madrid,Club de Golf', city: 'Madrid Alrededores' },
    { name: 'Las Rozas de Madrid,Molino de Hoz', city: 'Madrid Alrededores' },
    { name: 'Las Rozas de Madrid,El Pinar-Punta Galea', city: 'Madrid Alrededores' },
    { name: 'Las Rozas de Madrid,El Cantizal', city: 'Madrid Alrededores' },
    { name: 'Las Rozas de Madrid,Las Matas-Peñascales', city: 'Madrid Alrededores' },
    { name: 'Las Rozas de Madrid,Monte Rozas', city: 'Madrid Alrededores' },
    { name: 'Las Rozas de Madrid,Herón City-Montecillo-Európolis', city: 'Madrid Alrededores' },
    { name: 'Las Rozas de Madrid,Rozas Centro', city: 'Madrid Alrededores' },
    { name: 'Las Rozas de Madrid,El Burgo', city: 'Madrid Alrededores' },
    { name: 'Las Rozas de Madrid,Marazuela-El Torreón', city: 'Madrid Alrededores' },
    { name: 'Majadahonda', city: 'Madrid Alrededores' },
    { name: 'Pozuelo de Alarcón,Monteclaro-Montealina-La Cabaña-Prado Largo', city: 'Madrid Alrededores' },
    { name: 'Pozuelo de Alarcón,Zona Norte', city: 'Madrid Alrededores' },
    { name: 'Pozuelo de Alarcón,Zona Estación', city: 'Madrid Alrededores' },
    { name: 'Pozuelo de Alarcón,Zona Pueblo', city: 'Madrid Alrededores' },
    { name: 'Pozuelo de Alarcón,Zona de Avenida Europa', city: 'Madrid Alrededores' },
    { name: 'Pozuelo de Alarcón,Prado de Somosaguas-La Finca', city: 'Madrid Alrededores' },
    { name: 'Pozuelo de Alarcón,Somosaguas', city: 'Madrid Alrededores' },
    { name: 'Getafe', city: 'Madrid Alrededores' },
    { name: 'Leganés', city: 'Madrid Alrededores' },

    { name: 'Centro,La Trinidad', city: 'Málaga' },
    { name: 'Centro,Perchel Norte', city: 'Málaga' },
    { name: 'Centro,Perchel Sur- El Bulto', city: 'Málaga' },
    { name: 'Centro,Ensanche Centro-Soho', city: 'Málaga' },
    { name: 'Centro,Centro Histórico', city: 'Málaga' },
    { name: 'Centro,La Goleta-San Felipe Neri', city: 'Málaga' },
    { name: 'Centro,El Molinillo Capuchinos', city: 'Málaga' },
    { name: 'Centro,El Ejido-La Merced', city: 'Málaga' },
    { name: 'Centro,La Victoria-Conde de Ureña-Gibralfaro', city: 'Málaga' },
    { name: 'Bailen-Miraflores', city: 'Málaga' },
    { name: 'Teatinos', city: 'Málaga' },
    { name: 'Cruz de Humilladero', city: 'Málaga' },
    { name: 'Churriana', city: 'Málaga' },
    { name: 'Martiricos-Las Rocas', city: 'Málaga' },
    { name: 'Ciudad Jardín', city: 'Málaga' },
    { name: 'Campanillas', city: 'Málaga' },
    { name: 'Este,Malagueta-Monte Sancha', city: 'Málaga' },
    { name: 'Este,Limonar', city: 'Málaga' },
    { name: 'Este,Mayorazgo- Parque Clavero', city: 'Málaga' },
    { name: 'Este,Pedregalejo-Morlaco-Baños del Carmen', city: 'Málaga' },
    { name: 'Este,Cerrado de Calderón-Hacienda Paredes', city: 'Málaga' },
    { name: 'Este,Pinares de San Antón', city: 'Málaga' },
    { name: 'Este,El Palo', city: 'Málaga' },
    { name: 'Este,El Candado', city: 'Málaga' },

    { name: 'San Pedro Alcántara,Guadalmina Alta', city: 'Marbella' },
    { name: 'San Pedro Alcántara,Guadalmina Baja', city: 'Marbella' },
    { name: 'San Pedro Alcántara,San Pedro Pueblo', city: 'Marbella' },
    { name: 'San Pedro Alcántara,Linda Vista-Nueva Alcántara-Cortijo Blanco', city: 'Marbella' },
    { name: 'Nueva Andalucía,Puerto Banús', city: 'Marbella' },
    { name: 'Nueva Andalucía,Rodeo Alto-Guadaiza-La Campana', city: 'Marbella' },
    { name: 'Nueva Andalucía,Nueva Andalucía', city: 'Marbella' },
    { name: 'Nueva Andalucía,La Dama de Noche-La Alzambra', city: 'Marbella' },
    { name: 'Nueva Andalucía,Los Naranjos', city: 'Marbella' },
    { name: 'Nueva Andalucía,Las Brisas', city: 'Marbella' },
    { name: 'Nueva Andalucía,Aloha', city: 'Marbella' },
    { name: 'Nagüeles-Milla de Oro,Lomas de Marbella Club-Puente Romano', city: 'Marbella' },
    { name: 'Nagüeles-Milla de Oro,La Carolina-Guadalpín', city: 'Marbella' },
    { name: 'Nagüeles-Milla de Oro,Sierra Blanca', city: 'Marbella' },
    { name: 'Nagüeles-Milla de Oro,Nagüeles', city: 'Marbella' },
    { name: 'Marbella Pueblo,Playa de la Fontanilla', city: 'Marbella' },
    { name: 'Marbella Pueblo,Playa Bajadilla-Puertos', city: 'Marbella' },
    { name: 'Marbella Pueblo,Casco Antiguo', city: 'Marbella' },
    { name: 'Marbella Pueblo,Ricardo Soriano', city: 'Marbella' },
    { name: 'Marbella Pueblo,La Puya-La Hermita', city: 'Marbella' },
    { name: 'Marbella Pueblo,Miraflores-Divina Pastora', city: 'Marbella' },
    { name: 'Marbella Pueblo,Valdeolletas-Las Cancelas-Xarblanca', city: 'Marbella' },
    { name: 'Río Real-Los Monteros,Río Real', city: 'Marbella' },
    { name: 'Río Real-Los Monteros,Bello Horizonte-Lindasol', city: 'Marbella' },
    { name: 'Río Real-Los Monteros,Alto de los Monteros', city: 'Marbella' },
    { name: 'Río Real-Los Monteros,Bahía de Marbella', city: 'Marbella' },
    { name: 'Río Real-Los Monteros,Los Monteros', city: 'Marbella' },
    { name: 'Las Chapas-El Rosario,Santa Clara', city: 'Marbella' },
    { name: 'Las Chapas-El Rosario,El Rosario-Ricmar', city: 'Marbella' },
    { name: 'Las Chapas-El Rosario,Costabella', city: 'Marbella' },
    { name: 'Las Chapas-El Rosario,Las Chapas-Alicate Playa', city: 'Marbella' },
    { name: 'Elviria-Cabopino,Elviria', city: 'Marbella' },
    { name: 'Elviria-Cabopino,Santa María', city: 'Marbella' },
    { name: 'Elviria-Cabopino,Real de Zaragoza', city: 'Marbella' },
    { name: 'Elviria-Cabopino,Romana Playa', city: 'Marbella' },
    { name: 'Elviria-Cabopino,Hacienda Las Chapas', city: 'Marbella' },
    { name: 'Elviria-Cabopino,Marbesa', city: 'Marbella' },
    { name: 'Elviria-Cabopino,Reserva de Marbella', city: 'Marbella' },
    { name: 'Elviria-Cabopino,Cabopino-Artola', city: 'Marbella' },

    { name: 'Alaior', city: 'Menorca' },
    { name: 'Ciutadella de Menorca', city: 'Menorca' },
    { name: 'Es Castell', city: 'Menorca' },
    { name: 'Es Mercadal', city: 'Menorca' },
    { name: 'Sant Lluis', city: 'Menorca' },
    { name: 'Ferreries', city: 'Menorca' },
    { name: 'Mahón', city: 'Menorca' },

    { name: 'Centro-Argentina', city: 'Mérida' },
    { name: 'Los Milagros-Corchera', city: 'Mérida' },
    { name: 'Bodegones-Salesianos', city: 'Mérida' },
    { name: 'Nueva Ciudad', city: 'Mérida' },

    { name: 'Centro', city: 'Miranda de Ebro' },
    { name: 'Crucero-Aquende', city: 'Miranda de Ebro' },
    { name: 'La Charca', city: 'Miranda de Ebro' },
    { name: 'Anduva-Miranda Sur', city: 'Miranda de Ebro' },

    { name: 'Monzón', city: 'Monzón' },

    { name: 'Centro', city: 'Murcia' },
    { name: 'Norte', city: 'Murcia' },
    { name: 'Sur', city: 'Murcia' },
    { name: 'Pedanías Norte', city: 'Murcia' },
    { name: 'Pedanías Oeste', city: 'Murcia' },
    { name: 'Pedanias Este', city: 'Murcia' },
    { name: 'Campo de Murcia', city: 'Murcia' },

    { name: 'Centro', city: 'Orense' },
    { name: 'Casco Viejo', city: 'Orense' },
    { name: 'Posío', city: 'Orense' },
    { name: 'Universidad', city: 'Orense' },
    { name: 'Couto', city: 'Orense' },
    { name: 'A Carballeira', city: 'Orense' },
    { name: 'Barrocanes', city: 'Orense' },
    { name: 'A Ponte', city: 'Orense' },
    { name: 'O Vinteum', city: 'Orense' },

    { name: 'Centro-Casco histórico', city: 'Oviedo' },
    { name: 'Buenavista-La Ería-Montecerrao', city: 'Oviedo' },
    { name: 'Ciudad Naranco-Vallobín-La Florida', city: 'Oviedo' },
    { name: 'Corredoría-Huca-Teatinos', city: 'Oviedo' },
    { name: 'Fozaneldi-Tenderina-Ventanielles', city: 'Oviedo' },
    { name: 'San Lazaro-Otero-Villafría', city: 'Oviedo' },

    { name: 'Centro', city: 'Palencia' },
    { name: 'Cardenal Cisneros', city: 'Palencia' },
    { name: 'Hospital-Cacherriquilla', city: 'Palencia' },
    { name: 'Eras del Bosque-San Juanillo', city: 'Palencia' },
    { name: 'Ave María', city: 'Palencia' },
    { name: 'San Antonio', city: 'Palencia' },
    { name: 'El Cristo-Tejera', city: 'Palencia' },

    { name: 'Ciutat Antigua,La LLotja', city: 'Palma de Mallorca' },
    { name: 'Ciutat Antigua,La Seu-Cort-Monti-Sion', city: 'Palma de Mallorca' },
    { name: 'Ciutat Antigua,Sant Jaume', city: 'Palma de Mallorca' },
    { name: 'Ciutat Antigua,Sindicat', city: 'Palma de Mallorca' },
    { name: 'Ciutat Antigua,La Missio-Mercat', city: 'Palma de Mallorca' },
    { name: 'Es Forti-Son Cotoner-Son Dameto', city: 'Palma de Mallorca' },
    { name: 'Las Avenidas,Foners', city: 'Palma de Mallorca' },
    { name: 'Las Avenidas,Pere Grau', city: 'Palma de Mallorca' },
    { name: 'Las Avenidas,Marqués de la Fontsanta-Arxiduc', city: 'Palma de Mallorca' },
    { name: 'Las Avenidas,Bons Aires', city: 'Palma de Mallorca' },
    { name: 'Llevant-La Soledat', city: 'Palma de Mallorca' },
    { name: 'Son Oliva-Plaza Toros-Camp Redó', city: 'Palma de Mallorca' },
    { name: 'Portixol-Son Molinar', city: 'Palma de Mallorca' },
    { name: 'Rafal-Son Forteza', city: 'Palma de Mallorca' },
    { name: 'La Vileta-Son Rapinya', city: 'Palma de Mallorca' },
    { name: 'Son Vida', city: 'Palma de Mallorca' },
    { name: 'Sta Catalina-Son Armadans-Maritim,El Terreno', city: 'Palma de Mallorca' },
    { name: 'Sta Catalina-Son Armadans-Maritim,Paseo Marítimo', city: 'Palma de Mallorca' },
    { name: 'Sta Catalina-Son Armadans-Maritim,Son Armadams', city: 'Palma de Mallorca' },
    { name: 'Sta Catalina-Son Armadans-Maritim,Santa Catalina-El Jonquet', city: 'Palma de Mallorca' },
    { name: 'Sta Catalina-Son Armadans-Maritim,Son Espanyolet', city: 'Palma de Mallorca' },

    { name: 'Llucmajor,Llucmajor Interior', city: 'Palma de Mallorca Alrededores' },
    { name: 'Llucmajor,Cala Pi-Vallgornera', city: 'Palma de Mallorca Alrededores' },
    { name: 'Llucmajor,Badia Blava-Badia Gran-Tolleric', city: 'Palma de Mallorca Alrededores' },
    { name: 'Llucmajor,Sa Torre', city: 'Palma de Mallorca Alrededores' },
    { name: 'Llucmajor,Maioris-Puig de Ros', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Calviá Pueblo', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Peguera', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Costa de la Calma', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Santa Ponça', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,El Toro', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Sol de Mallorca', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Cala Vinyes', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Magaluf', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Son Ferrer', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Palmanova-Son Caliu', city: 'Palma de Mallorca Alrededores' },
    { name: `Calviá,Costa d'en Blanes`, city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Portals Nous-Bendinat', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Cas Catala', city: 'Palma de Mallorca Alrededores' },
    { name: 'Calviá,Illetes', city: 'Palma de Mallorca Alrededores' },
    { name: 'Campos-Sa Rápita', city: 'Palma de Mallorca Alrededores' },
    { name: 'Ses Salines-Colonia de Sant Jordi', city: 'Palma de Mallorca Alrededores' },
    { name: `Sastanyí-Portopetro-Cala D'Or`, city: 'Palma de Mallorca Alrededores' },
    { name: 'Felanitx-Porto Colom', city: 'Palma de Mallorca Alrededores' },
    { name: 'Manacor Centro', city: 'Palma de Mallorca Alrededores' },
    { name: 'Son Servera-Sant Llorenç', city: 'Palma de Mallorca Alrededores' },
    { name: 'Capdepera', city: 'Palma de Mallorca Alrededores' },
    { name: 'Artá', city: 'Palma de Mallorca Alrededores' },
    { name: 'Santa Margalida-Can Picafort', city: 'Palma de Mallorca Alrededores' },
    { name: 'Muro', city: 'Palma de Mallorca Alrededores' },
    { name: 'Sa Pobla', city: 'Palma de Mallorca Alrededores' },
    { name: 'Alcudia', city: 'Palma de Mallorca Alrededores' },
    { name: 'Pollença', city: 'Palma de Mallorca Alrededores' },
    { name: 'Campanet-Bruger', city: 'Palma de Mallorca Alrededores' },
    { name: 'Selva', city: 'Palma de Mallorca Alrededores' },
    { name: 'Inca', city: 'Palma de Mallorca Alrededores' },
    { name: 'Sóller', city: 'Palma de Mallorca Alrededores' },
    { name: 'Deià-Bunyola', city: 'Palma de Mallorca Alrededores' },
    { name: 'Valldemossa', city: 'Palma de Mallorca Alrededores' },
    { name: `Port d' Andratx`, city: 'Palma de Mallorca Alrededores' },
    { name: 'Esporles-Puigpunyet-Estellencs-Banyalbufar', city: 'Palma de Mallorca Alrededores' },
    { name: 'Marratxí', city: 'Palma de Mallorca Alrededores' },
    { name: 'Santa María del Camí', city: 'Palma de Mallorca Alrededores' },
    { name: 'Binissalem', city: 'Palma de Mallorca Alrededores' },
    { name: 'Algaida', city: 'Palma de Mallorca Alrededores' },
    { name: 'Porreres-Montuíri', city: 'Palma de Mallorca Alrededores' },
    { name: 'Sineu-Llubí-Petra', city: 'Palma de Mallorca Alrededores' },

    { name: 'Leskairu', city: 'Pamplona' },
    { name: 'Casco Antiguo', city: 'Pamplona' },
    { name: 'Segundo Ensanche', city: 'Pamplona' },
    { name: 'Iturrama', city: 'Pamplona' },
    { name: 'Azpilagaña', city: 'Pamplona' },
    { name: 'Milagrosa', city: 'Pamplona' },
    { name: 'Rochapea', city: 'Pamplona' },
    { name: 'San Juan', city: 'Pamplona' },
    { name: 'Primer Ensanche', city: 'Pamplona' },
    { name: 'Chantrea', city: 'Pamplona' },

    { name: 'Centro', city: 'Peñíscola' },
    { name: 'Centro Casco Antiguo', city: 'Peñíscola' },
    { name: 'Llandels', city: 'Peñíscola' },
    { name: 'Las Atalayas-Urmi-Cerro Mar', city: 'Peñíscola' },
    { name: 'Playa Norte', city: 'Peñíscola' },

    { name: 'La Volta', city: 'Ponferrada' },
    { name: 'Flores del Sil', city: 'Ponferrada' },
    { name: 'Zona Alta', city: 'Ponferrada' },

    { name: 'Centro-Echegaray', city: 'Pontevedra' },
    { name: 'Campo da Torre-Mollabao', city: 'Pontevedra' },
    { name: 'Zona Maria Victoria Moreno', city: 'Pontevedra' },
    { name: 'Zona Plaza de Barcelos', city: 'Pontevedra' },
    { name: 'Los Seca-Los Salgueriños', city: 'Pontevedra' },

    { name: 'Portugalete', city: 'Portugalete' },

    { name: 'Centro', city: 'Puertollano' },
    { name: 'El Poblado-Abulagar', city: 'Puertollano' },
    { name: 'Carretera de Córdoba-Libertad', city: 'Puertollano' },
    { name: 'Las Mercedes-El Carmen', city: 'Puertollano' },
    { name: 'Pau 2 - 600', city: 'Puertollano' },

    { name: 'Centro,Centro', city: 'Salamanca' },
    { name: 'Centro,Sancti Spíritus-San Juan-San Vicente-Las Úrsulas-Universidad-Tenerías', city: 'Salamanca' },
    { name: 'Centro,San Esteban-San Cristóbal', city: 'Salamanca' },
    { name: 'Vidal', city: 'Salamanca' },
    { name: 'Barrio Blanco', city: 'Salamanca' },
    { name: 'Pizarrales', city: 'Salamanca' },
    { name: 'San Bernardo-Carmelitas-Campus', city: 'Salamanca' },
    { name: 'La Salle-Vistahermosa', city: 'Salamanca' },
    { name: 'San José-Parador-Zurgue', city: 'Salamanca' },
    { name: 'Prosperidad-Delicias', city: 'Salamanca' },
    { name: 'Chinchibarra-Capuchinos', city: 'Salamanca' },
    { name: 'Garrido', city: 'Salamanca' },
    { name: 'Rollo-Puente Ladrillo', city: 'Salamanca' },

    { name: 'Centro-Miraconcha,Miraconcha', city: 'San Sebastián' },
    { name: 'Centro-Miraconcha,Amara Zaharra-Arbaizenea', city: 'San Sebastián' },
    { name: 'Centro-Miraconcha,Área Romántica', city: 'San Sebastián' },
    { name: 'Antiguo', city: 'San Sebastián' },
    { name: 'Parte Vieja', city: 'San Sebastián' },
    { name: 'Gros', city: 'San Sebastián' },
    { name: 'Egia', city: 'San Sebastián' },
    { name: 'Amara', city: 'San Sebastián' },
    { name: 'Ategorrieta-Ulia', city: 'San Sebastián' },
    { name: 'Intxaurrondo', city: 'San Sebastián' },
    { name: 'Aiete-Ibaeta-Igeldo', city: 'San Sebastián' },
    { name: 'Añorga-Miramón-Zorroaga-Loiola-Martutene', city: 'San Sebastián' },

    { name: 'Centro - Ayuntamiento', city: 'Sanlúcar de Barrameda' },
    { name: 'V Centenario-Piletas-Capuchinos', city: 'Sanlúcar de Barrameda' },
    { name: 'Ayuntamiento-Barrio Alto', city: 'Sanlúcar de Barrameda' },
    { name: 'Centro-Calzada-Cabo Noval', city: 'Sanlúcar de Barrameda' },
    { name: 'El Pino-Bajo de Guía', city: 'Sanlúcar de Barrameda' },

    { name: 'El Sardinero', city: 'Santander' },
    { name: 'Alisal-Cazoña-San Román', city: 'Santander' },
    { name: 'Penacastillo-Nuevamontaña', city: 'Santander' },
    { name: 'Centro-Ayuntamiento', city: 'Santander' },
    { name: 'Castilla-Hermida', city: 'Santander' },
    { name: 'Cuatro Caminos', city: 'Santander' },
    { name: 'Puerto Chico', city: 'Santander' },
    { name: 'Numancia-San Fernando', city: 'Santander' },
    { name: 'Los Castros', city: 'Santander' },
    { name: 'Monte', city: 'Santander' },
    { name: 'Valdenoja', city: 'Santander' },

    { name: 'Casco Histórico', city: 'Santiago de Compostela' },
    { name: 'Ensanche Sar', city: 'Santiago de Compostela' },
    { name: 'Concheiro-Fontiñas', city: 'Santiago de Compostela' },
    { name: 'Campus Norte-S.Caetano', city: 'Santiago de Compostela' },
    { name: 'San Lázaro-Meixonfrio', city: 'Santiago de Compostela' },
    { name: 'Castiñeiriño-Cruceiro do Sar', city: 'Santiago de Compostela' },
    { name: 'Conxo', city: 'Santiago de Compostela' },
    { name: 'Campus Sur-Santa Marta', city: 'Santiago de Compostela' },

    { name: 'Centro', city: 'Segovia' },
    { name: 'Plaza Mayor-San Agustín', city: 'Segovia' },
    { name: 'San Lorenzo-San Marcos', city: 'Segovia' },
    { name: 'José Zorrila', city: 'Segovia' },
    { name: 'Plaza de Toros', city: 'Segovia' },
    { name: 'El Carmen', city: 'Segovia' },

    { name: 'Centro,Encarnación-Las Setas', city: 'Sevilla' },
    { name: 'Centro,Plaza de la Gavidia-San Lorenzo', city: 'Sevilla' },
    { name: 'Centro,San Vicente', city: 'Sevilla' },
    { name: 'Centro,Arenal-Museo', city: 'Sevilla' },
    { name: 'Centro,Santa Cruz-Alfalfa-Puerta de la Carne-Juderia', city: 'Sevilla' },
    { name: 'Centro,Puerta Carmona-Puerta Osario-Amador de los Ríos', city: 'Sevilla' },
    { name: 'Centro,San Julián', city: 'Sevilla' },
    { name: 'Centro,Feria', city: 'Sevilla' },
    { name: 'Centro,Alameda', city: 'Sevilla' },
    { name: 'Prado de San Sebastián-Felipe II-Bueno Monreal', city: 'Sevilla' },
    { name: 'Macarena', city: 'Sevilla' },
    { name: 'Santa Justa, Miraflores-Cruz Roja', city: 'Sevilla' },
    { name: 'San Pablo', city: 'Sevilla' },
    { name: 'Santa Clara', city: 'Sevilla' },
    { name: 'Nervión,Nervión', city: 'Sevilla' },
    { name: 'Nervión,San Bernardo-Buhaira-Huerta del Rey', city: 'Sevilla' },
    { name: 'Nervión,Luis Montoto-Santa Justa', city: 'Sevilla' },
    { name: 'Nervión,Gran Plaza-Marqués de Pickman-Ciudad Jardín-El Juncal-El Porvenir', city: 'Sevilla' },
    { name: 'Triana', city: 'Sevilla' },
    { name: 'Los Remedios', city: 'Sevilla' },
    { name: 'La Palmera-Los Bermejales', city: 'Sevilla' },
    { name: 'Bellavista-Jardines de Hércules', city: 'Sevilla' },
    { name: 'Cerro Amate', city: 'Sevilla' },
    { name: 'Pino Montano-San Jéronimo', city: 'Sevilla' },
    { name: 'Sevilla Este', city: 'Sevilla' },
    { name: 'Torreblanca', city: 'Sevilla' },

    { name: 'Soria', city: 'Soria' },

    { name: 'Casco Antiguo', city: 'Talavera de la Reina' },
    { name: 'Puerta de Cuartos-Avenida de Portugal', city: 'Talavera de la Reina' },
    { name: 'Tres Olivos-La Piedad', city: 'Talavera de la Reina' },
    { name: 'El Pilar-La Estación', city: 'Talavera de la Reina' },
    { name: 'Hospital-Nuevo Centro', city: 'Talavera de la Reina' },
    { name: 'Centro-Corte Inglés', city: 'Talavera de la Reina' },

    { name: 'Barris Maritims', city: 'Tarragona' },
    { name: 'Nou Eixample Sud', city: 'Tarragona' },
    { name: 'Eixample', city: 'Tarragona' },
    { name: 'Part Alta', city: 'Tarragona' },
    { name: 'Torreforta', city: 'Tarragona' },
    { name: 'Nou Eixample Nord', city: 'Tarragona' },
    { name: 'Sant Pere i Sant Pau', city: 'Tarragona' },

    { name: 'Reus,Ponent', city: 'Tarragona Alrededores' },
    { name: 'Reus,Centre', city: 'Tarragona Alrededores' },
    { name: 'Reus,Mestral', city: 'Tarragona Alrededores' },
    { name: 'Reus,Llevant', city: 'Tarragona Alrededores' },
    { name: 'Reus,Migjorn', city: 'Tarragona Alrededores' },
    { name: 'Calafell,Platja Calafell', city: 'Tarragona Alrededores' },
    { name: 'Calafell,Segur Platja', city: 'Tarragona Alrededores' },
    { name: 'Calafell,Segur de Calafell', city: 'Tarragona Alrededores' },
    { name: 'Calafell,Mas Mel Bellamar', city: 'Tarragona Alrededores' },
    { name: 'Calafell,Calafell Pueblo', city: 'Tarragona Alrededores' },
    { name: 'Cunit,Residencial', city: 'Tarragona Alrededores' },
    { name: 'Cunit,Can Toni', city: 'Tarragona Alrededores' },
    { name: 'Cunit,Centre-Diagonal-Cunidor-Prat de Cunit', city: 'Tarragona Alrededores' },
    { name: 'Cunit,Valparaiso', city: 'Tarragona Alrededores' },
    { name: 'El Vendrell,Bonavista', city: 'Tarragona Alrededores' },
    { name: 'El Vendrell,Sant Salvador', city: 'Tarragona Alrededores' },
    { name: 'El Vendrell,Coma-Ruga', city: 'Tarragona Alrededores' },
    { name: 'El Vendrell,Els Masos', city: 'Tarragona Alrededores' },
    { name: 'El Vendrell,Ponent-Barri de França', city: 'Tarragona Alrededores' },
    { name: 'El Vendrell,La Muntanyeta-La Franquesa', city: 'Tarragona Alrededores' },
    { name: 'Urbanitzacions de Llevant', city: 'Tarragona Alrededores' },

    { name: 'Teruel', city: 'Teruel' },

    { name: 'Buenavista,Valparaiso-La legua', city: 'Toledo' },
    { name: 'Casco Histórico', city: 'Toledo' },
    { name: 'Santa Bárbara', city: 'Toledo' },
    { name: 'Avenida Europa-San Antón', city: 'Toledo' },

    { name: 'Tomelloso', city: 'Tomelloso' },

    { name: 'Torrelavega', city: 'Torrelavega' },

    { name: 'Tudela', city: 'Tudela' },
    { name: 'Ciutat Vella,El Mercat', city: 'Valencia' },
    { name: 'Ciutat Vella,La Seu', city: 'Valencia' },
    { name: 'Ciutat Vella,El Carme', city: 'Valencia' },
    { name: 'Ciutat Vella,El Pilar', city: 'Valencia' },
    { name: 'Ciutat Vella,La Xerea', city: 'Valencia' },
    { name: 'Ciutat Vella,Sant Francesc', city: 'Valencia' },
    { name: 'Extramurs,La Petxina', city: 'Valencia' },
    { name: 'Extramurs,Arrancapins', city: 'Valencia' },
    { name: 'Extramurs,La Roqueta', city: 'Valencia' },
    { name: 'Extramurs,El Botánic', city: 'Valencia' },
    {
        name: `L'Eixample, El Pla del Remei`, city: 'Valencia'
    },
    {
        name: `L'Eixample, Russafa`, city: 'Valencia'
    },
    {
        name: `L'Eixample, Gran Vía`, city: 'Valencia'
    },
    { name: 'El Pla del real', city: 'Valencia' },
    { name: 'La Saidia,Tormos', city: 'Valencia' },
    { name: 'La Saidia,Marxalenes', city: 'Valencia' },
    { name: 'La Saidia,Sant Antoni', city: 'Valencia' },
    { name: 'La Saidia,Morvedre', city: 'Valencia' },
    { name: 'La Saidia,Trinitat', city: 'Valencia' },
    {
        name: `L'Olivereta, Nou Moles`, city: 'Valencia'
    },
    {
        name: `L'Olivereta, Tres Forques`, city: 'Valencia'
    },
    {
        name: `L'Olivereta, Soternes - La Llum`, city: 'Valencia'
    },
    { name: 'Patraix,Patraix-Safranar', city: 'Valencia' },
    { name: 'Patraix,Sant Insidre-Vara de Quart-Barrio de Favara', city: 'Valencia' },
    { name: 'Jesús,La Raiosa', city: 'Valencia' },
    {
        name: `Jesús,L'Hort de Senabre`, city: 'Valencia'
    },
    { name: 'Jesús,La Creu Coberta-Sant Marcellí-Camí Reial', city: 'Valencia' },
    { name: 'Quatre Carreres,Malilla', city: 'Valencia' },
    { name: 'Quatre Carreres,En Corts-Mont-Olivet', city: 'Valencia' },
    { name: 'Quatre Carreres,Ciutat de las Artes i las Ciencies', city: 'Valencia' },
    { name: 'Quatre Carreres,La Punta', city: 'Valencia' },
    { name: 'Quatre Carreres,Na Rovella-Fonteta de Sant Lluis', city: 'Valencia' },
    { name: 'Camins al Grau,Camí Fondo-Albors', city: 'Valencia' },
    { name: 'Camins al Grau,Aiora', city: 'Valencia' },
    { name: 'Camins al Grau,La Creu del Grau', city: 'Valencia' },
    { name: 'Camins al Grau,Penya-Roja', city: 'Valencia' },
    { name: 'Algirós', city: 'Valencia' },
    { name: 'Benimaclet', city: 'Valencia' },
    { name: 'Rascanya,Torrefiel', city: 'Valencia' },
    { name: 'Rascanya,Els Orriols', city: 'Valencia' },
    { name: 'Rascanya,Sant Llorenç', city: 'Valencia' },
    { name: 'Benicalap,Benicalap', city: 'Valencia' },
    { name: 'Benicalap,Nou Benicalap', city: 'Valencia' },
    { name: 'Benicalap,Ciutat Fallera', city: 'Valencia' },
    { name: 'Campanar', city: 'Valencia' },

    { name: 'Centro', city: 'Valladolid' },
    { name: 'Rondilla-Santa Clara', city: 'Valladolid' },
    { name: 'Hospital-San Juan-Circular-Vadillos', city: 'Valladolid' },
    { name: 'Campo Grande-Arco Ladrillo', city: 'Valladolid' },
    { name: 'Delicias', city: 'Valladolid' },
    { name: 'Paseo Zorrilla-Cuatro de Marzo', city: 'Valladolid' },
    { name: 'Huerta del Rey', city: 'Valladolid' },
    { name: 'Parquesol', city: 'Valladolid' },
    { name: 'Arturo Eyre-La Rubia', city: 'Valladolid' },
    { name: 'Pajarillos', city: 'Valladolid' },
    { name: 'Las Villas-Santa Ana-Covaresa-Parque Alameda', city: 'Valladolid' },
    { name: 'La Victoria-El Cabildo', city: 'Valladolid' },
    { name: 'Arcas Reales-Pinar del Jalón-Hospital Nuevo', city: 'Valladolid' },
    { name: 'Belén-Pilarica-Bo España', city: 'Valladolid' },

    { name: 'Centro-Areal', city: 'Vigo' },
    { name: 'Casco Vello', city: 'Vigo' },
    { name: 'Plaza España-Corte Inglés', city: 'Vigo' },
    { name: 'Fátima-Travesia de Vigo-San Xoán', city: 'Vigo' },
    { name: 'Casablanca-Calvario', city: 'Vigo' },
    { name: 'O Castro', city: 'Vigo' },
    { name: 'Camelias-Pi i Margall', city: 'Vigo' },
    { name: 'Plaza Independencia', city: 'Vigo' },
    { name: 'A Salgueira-O Castaño', city: 'Vigo' },
    { name: 'Berbés-Peritos', city: 'Vigo' },
    { name: 'Plaza de la Industria', city: 'Vigo' },
    { name: 'Bouzas', city: 'Vigo' },
    { name: 'Coia', city: 'Vigo' },
    { name: 'As Travesas-Balaídos', city: 'Vigo' },

    { name: 'Villarobledo', city: 'Villareal' },
    { name: 'Madrigal', city: 'Villareal' },
    { name: 'Barrio del Pilar', city: 'Villareal' },
    { name: 'Piscinas', city: 'Villareal' },
    { name: 'Centro', city: 'Villareal' },
    { name: 'Cariñena', city: 'Villareal' },

    { name: 'Avenida Alemania-Avenida Italia', city: 'Villarobledo' },

    { name: 'Vinarós', city: 'Vinarós' },

    { name: 'Casco Viejo', city: 'Vitoria' },
    { name: 'Coronación', city: 'Vitoria' },
    { name: 'Centro', city: 'Vitoria' },
    { name: 'Judimendi-Santa Lucía-Santiago-El Anglo', city: 'Vitoria' },
    { name: 'Aranzabela-Aranbiskarra-Zaramaga', city: 'Vitoria' },
    { name: 'Zabalgana-Ariznabarra', city: 'Vitoria' },
    { name: 'Armentia-Ciudad Jardín', city: 'Vitoria' },
    { name: 'Aretxabaleta-San Cristobal-Adurtxa', city: 'Vitoria' },
    { name: 'Salburua', city: 'Vitoria' },
    { name: 'Lakua-Arriaga', city: 'Vitoria' },
    { name: 'Lovaina-Aranzabal', city: 'Vitoria' },
    { name: 'San Martín-Txagorritxu', city: 'Vitoria' },
    { name: 'El Pilar', city: 'Vitoria' },

    { name: 'Ensanche', city: 'Zamora' },
    { name: 'Pantoja-Vista Alegre', city: 'Zamora' },
    { name: 'Los Bloques', city: 'Zamora' },
    { name: 'La Candelaria', city: 'Zamora' },
    { name: 'Centro', city: 'Zamora' },
    { name: 'La Lana', city: 'Zamora' },
    { name: 'Casco Antiguo', city: 'Zamora' },
    { name: 'Las Vegas-La Feria', city: 'Zamora' },
    { name: 'San Lázaro', city: 'Zamora' },

    { name: 'Torrero- La Paz-Pinares de Venecia', city: 'Zaragoza' },
    { name: 'Parque Venecia', city: 'Zaragoza' },
    { name: 'Arrabal-Barrio Jesús', city: 'Zaragoza' },
    { name: 'Actur', city: 'Zaragoza' },
    { name: 'Almozara', city: 'Zaragoza' },
    { name: 'Casablanca', city: 'Zaragoza' },
    { name: 'Universidad,Ciudad Universitaria', city: 'Zaragoza' },
    { name: 'Universidad,Romareda', city: 'Zaragoza' },
    { name: 'Oliver', city: 'Zaragoza' },
    { name: 'Valdefierro', city: 'Zaragoza' },
    { name: 'Salvador Allende-Parque Goya-Zorongo', city: 'Zaragoza' },
    { name: 'San José', city: 'Zaragoza' },
    { name: 'Centro,Doctor Cerrada', city: 'Zaragoza' },
    { name: 'Centro,Paseo Sagasta', city: 'Zaragoza' },
    { name: 'Centro,Paseo de la Consitución-Las Damas', city: 'Zaragoza' },
    { name: 'Centro,Paseo Independencia', city: 'Zaragoza' },
    { name: 'Casco Historico,San Pablo', city: 'Zaragoza' },
    { name: 'Casco Historico,Alfonso-El Tubo', city: 'Zaragoza' },
    { name: 'Casco Historico,La Magdalena', city: 'Zaragoza' },
    { name: 'Casco Historico,Plaza de Toros', city: 'Zaragoza' },
    { name: 'Ruiseñores ', city: 'Zaragoza' },
    { name: 'Delicias,Barrio del Ave', city: 'Zaragoza' },
    { name: 'Delicias,Delicias', city: 'Zaragoza' },
    { name: 'Delicias,Mercado San Valero', city: 'Zaragoza' },
    { name: 'Delicias,Ciudad Jardín-Parque Roma', city: 'Zaragoza' },
    { name: 'Delicias,Parcelación Barcelona', city: 'Zaragoza' },
    { name: 'Delicias,Bombarda-Monsalud', city: 'Zaragoza' },
    { name: 'Las Fuentes-Cartuja Baja', city: 'Zaragoza' },
    { name: 'La Jota', city: 'Zaragoza' },
    { name: 'Avenida Cataluña-Santa Isabel-Movera', city: 'Zaragoza' },
]

const importData = async () => {
    let city_id = '';
    let city_name = '';
    for (let index = 0; index < data.length; index++) {
        try {
            const row = data[index];
            if (city_name !== row.city) {
                const newCity = await City.create({ name: row.city, banner: '' });
                city_name = newCity.name;
                city_id = newCity.id;
            }
            const newDistrict = await District.create({ name: row.name, city: city_id });
            console.log('imported:', newDistrict.name)
        } catch (e) {
            console.log('error =>>>>', e)
        }
    }
    console.log('Imported successfully.')
}

importData()